---
apiVersion: v1
kind: Service
metadata:
  name: postgres16-lb
  namespace: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres16.abchost.nl
    metallb.universe.tf/loadBalancerIPs: ${CLUSTER_CLOUDNATIVE_PG_16_IP}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres16
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: postgres16
    role: primary
