---
apiVersion: v1
kind: Service
metadata:
  name: &app external-volumio-ingress
  namespace: ingress
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  # These should point to the actual service
  externalName: "192.168.5.3"
  ports:
  - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app external-volumio-ingress
  namespace: ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ingressClassName: internal
  rules:
    # These are the ingress rules
    - host: &host volumio.abchost.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 443
      tls:
          - hosts:
              - *host