---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hyperhdr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: nocturno/hyper-hdr
      tag: amd64-19.0.0.0
    strategy:
      type: Recreate
    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
      - name: TZ
        value: "Europe/Amsterdam"
    service:
      main:
        ports:
          http:
            port: 8090
          json-api:
            port: 19444
    hostNetwork: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-internal
        hosts:
          - host: ambi.abrondijk.com
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: hyperhdr
        mountPath: /config
      usb-1:
        enabled: true
        type: hostPath
        hostPath: /dev/video0
        mountPath: /dev/video0
      usb-2:
        enabled: true
        type: hostPath
        hostPath: /dev/video1
        mountPath: /dev/video1
      usb-3:
        enabled: true
        type: hostPath
        hostPath: /dev/media0
        mountPath: /dev/media0
    securityContext:
      privileged: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/usb-ef_534d_2109.present
                  operator: In
                  values:
                    - "true"
