---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app immich-microservices
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: immich-database
      namespace: immich
  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.99.0
    args: ["start-microservices.sh"]
    strategy:
      type: Recreate
    envFrom:
      - secretRef:
          name: immich
      - configMapRef:
          name: immich
    env:
      - name: DB_DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: immich-database
            key: POSTGRES_DB
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: immich-database
            key: POSTGRES_USER
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: immich-database
            key: POSTGRES_PASSWORD
      - name: REVERSE_GEOCODING_DUMP_DIRECTORY
        value: /geodata-cache
      - name: PUID
        value: 1000
      - name: PGID
        value: 1000
    service:
      main:
        enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    persistence:
      geo-data:
        enabled: true
        type: pvc
        existingClaim: immich-microservices
        mountPath: /geodata-cache
      library:
        enabled: true
        type: nfs
        server: 192.168.2.210
        path: /mnt/MAIN/contain/storage/general/immich/library
        mountPath: /usr/src/app/upload/library
      thumbnail:
        enabled: true
        type: pvc
        existingClaim: immich-thumbs
        mountPath: /usr/src/app/upload/thumbs
      encoded-video:
        enabled: true
        type: nfs
        server: 192.168.2.210
        path: /mnt/MAIN/contain/storage/general/immich/encoded-videos
        mountPath: /usr/src/app/upload/encoded-video
      profile:
        enabled: true
        type: pvc
        existingClaim: immich-profile
        mountPath: /usr/src/app/upload/profile
      upload:
        enabled: true
        type: pvc
        existingClaim: immich-upload
        mountPath: /usr/src/app/upload/upload
