apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
type: Opaque
stringData:
    #ENC[AES256_GCM,data:H5A4aiZeu+B3mdLD432tsRg=,iv:hbYBu9GZJbnt5dzh/d4dohsofpCPKK21rGDi3588WUU=,tag:29RnuRlhu3O4RLLo3NLgjw==,type:comment]
    super-user-name: ENC[AES256_GCM,data:s1nn5TkyNc6a8klLYA==,iv:SMqOYMev6dpg+l29668yutT0dJCDsqR/Ys0XCMjoUwo=,tag:3RKpK9V9DvheFDuUVElsBA==,type:str]
    super-user-pass: ENC[AES256_GCM,data:obucSSZa0XBbOP30TtjGBxqfbL1xsw1s3GW7gxVZOFmrWkEkbklKbn1XWTmN4/2ecZ+uQPFyCWJJf5NBm6MjRw==,iv:llqASF2EcoiQdeDiKUwLEsyJmgmaaIGAGgnzXWwfFEc=,tag:m4rsk0nPTdBLJoISJPcW8A==,type:str]
    #ENC[AES256_GCM,data:Ml/0eT4ejKHrH9kfraPCEmZCSmetaYPSsgBp,iv:XOuu0mPmxoFe8eXiaUL6SqVXujwlUgqPwctjE/wPJ60=,tag:RXk0SMaGeUaAIG9A85RboA==,type:comment]
    backblaze-id: ENC[AES256_GCM,data:hqRkYIDKPWkLhxahdGHINt7+kFoHt7FZSA==,iv:T7PIw0SCzmO7X4TMkvLvm8W3mzI4fJyyAxRL8S68M4M=,tag:zZAFZPlxaAtMEbnSoM7p+Q==,type:str]
    backblaze-key: ENC[AES256_GCM,data:K3wew8v/cVm76AjlE63pEbcUMnFCO43nCelBwQ5DWQ==,iv:P+U3W5G6N43mJWGTNH2UPqtvmacEGetwlxuoEQ2GmXQ=,tag:X1KkYBd+Fi3meRy2nt3hUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
            NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
            RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
            Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
            6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T21:15:38Z"
    mac: ENC[AES256_GCM,data:cEfOLtJTDvoe24tg0MGeCRdiFrH9rciixGaGzAnR39yPLehN/mcQIWvB9amhgArsOdMyxv4nqbqCgZS65gSUppwrClm0zW+tcxi1IkFOcUp+fWzjXpWktPupe6Ga/P7WYA+R5RnzA+7jQjxW6RNR8xIhPO0T+dg8u4hmtW1pXDk=,iv:VLZ7y6GACaz3cI/mvctgSUQh51FH5evA5+Eo1TdL/Os=,tag:dIgp6uLnTbE4AZYuygRY4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-app-user
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:PypT,iv:MDxOm8jEovklxZ9Q+cBLNRXKZZReBCnztT4McTA+26o=,tag:2a11//tidPLOEE3vQNdXLQ==,type:str]
    password: ENC[AES256_GCM,data:+YFDy/rL80XAZwPMrUKubTHPSa8=,iv:VlAsumXufJjIUntnMsbzwO9j+Lk5FV9KagB2xZj0+NM=,tag:pBRptEsHdcqFL3zJi0rvIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
            NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
            RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
            Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
            6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T21:15:38Z"
    mac: ENC[AES256_GCM,data:cEfOLtJTDvoe24tg0MGeCRdiFrH9rciixGaGzAnR39yPLehN/mcQIWvB9amhgArsOdMyxv4nqbqCgZS65gSUppwrClm0zW+tcxi1IkFOcUp+fWzjXpWktPupe6Ga/P7WYA+R5RnzA+7jQjxW6RNR8xIhPO0T+dg8u4hmtW1pXDk=,iv:VLZ7y6GACaz3cI/mvctgSUQh51FH5evA5+Eo1TdL/Os=,tag:dIgp6uLnTbE4AZYuygRY4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
