apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: database
type: Opaque
stringData:
    REDIS-PASSWORD: ENC[AES256_GCM,data:/kwftcmqLKmT/7aPVd9Jw1nSz0bjA7eBZVdHZCH/4Gtk7G9ryx6bfmjIsx3SCU6mJPp3GgFD14Bw0COJ0d7Zeg==,iv:APsvn3E0m4xJ+ualjmvzOk7C0LVYqIYrCknzXUPor9Q=,tag:u8O2mpWr+K0xHugWbBMtFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU3BRWXg3dlRVd285RnZ2
            c1ViMkRTYnVDMzlObWd5UEFOZExTejU3cWprCjBvUGVWWlVUbUtRcXFXT21IMWJv
            WDJEREhwbnVXRFFKWklwUEVQdFZ2UXMKLS0tIFlySmEyZ21ucFpwZnhERCtDTlA3
            TmdBVkhGRzRmd2UzdTlrL3ZFZUlGS0EKzbOEduAElAKs69coxcKHPS/hm73sbHl1
            d6w0paLQ1yptBf3ZcBtofH7ezKzS3VwzSF9NSlytf1c+G523RqrH7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T19:38:50Z"
    mac: ENC[AES256_GCM,data:JEu92I/eXspa6rDxZ4mCiVvWLEOdili9yFBiSAeYLwPIx8/N6vMn/wcFuYb7dNgyFROoPs/BCMFlBXDad/Nfmvx2lQb1l402YZir7NSMEuSJqdYcFnBtEfpjrtd91GfwR1WjM2ZS4dkK1XW8kHc9UAquaMsIk8P4zkVSToXup7g=,iv:s42ed9/jr14NmqZr764Aah+t+JNZ6so/LjYUpFHupmM=,tag:1To62AIGYKxBFW69qoQ2qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
