---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-lidarr
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-longhorn
    - name: apps-prowlarr
    - name: apps-qbittorrent
    - name: cluster-apps-cloudnative-pg-cluster
  path: ./kubernetes/apps/user/media/lidarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
