---
# yaml-language-server: =https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: user-apps-jellyfin
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-longhorn
  path: ./kubernetes/apps/user/media/jellyfin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age