apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb-operator-crds
  namespace: flux-system
spec:
  targetNamespace: database
  path: ./kubernetes/apps/database/maria/crds
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  timeout: 5m