apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb
  namespace: flux-system
spec:
  dependsOn:
    - name: mariadb-operator
  targetNamespace: database
  path: ./kubernetes/apps/database/maria/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  timeout: 5m