---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-typesense
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: typesense/typesense
      tag: 0.24.1
    envFrom:
      - secretRef:
          name: typesense
    env:
      - name: TYPESENSE_DATA_DIR
        value: /data
    service:
      main:
        ports:
          http:
            port: &port 8108
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 3Gi
      limits:
        cpu: 1000m
        memory: 5Gi
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: immich-typesense
        mountPath: /data
