---
directories:
  downloads: /mnt/general/soulseek/complete
  incomplete: /mnt/general/soulseek/incomplete
flags:
  no_version_check: true
metrics:
  enabled: true
  url: /metrics
  authentication:
    disabled: true
permissions:
  file:
    mode: 750
remote_configuration: false
shares:
  directories:
    - /mnt/general/soulseek/shared
  filters:
    - \.ini$
    - Thumbs.db$
    - \.DS_Store$
    - album.nfo$
retention:
  search: 10080 # 7 days, in minutes
  transfers:
    upload:
      succeeded: 1440 # 1 day, in minutes
      errored: 30
      cancelled: 5
    download:
      succeeded: 1440 # 1 day, in minutes
      errored: 20160 # 2 weeks, in minutes
      cancelled: 5
  files:
    complete: 20160 # 2 weeks, in minutes
    incomplete: 43200 # 30 days, in minutes
  logs: 180 # days