---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-invoice-ninja-database
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-longhorn
  path: ./kubernetes/apps/infinigon/invoice-ninja/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-invoice-ninja
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager
    - name: cluster-apps-longhorn
    - name: apps-invoice-ninja-database
  path: ./kubernetes/apps/infinigon/invoice-ninja/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m