# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app blocky-frontend
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json
    controllers:
      blocky-frontend:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mozart409/blocky-frontend
              tag: v0.2.1
            envFrom:
              - configMapRef:
                  name: blocky-frontend
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8002
    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host "blocky.abchost.nl"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
                pathType: Prefix
        tls:
          - hosts:
              - *host
    serviceAccount:
      create: true
      name: *app
    serviceMonitor:
      app:
        enabled: false
        serviceName: *app
    persistence:
      srv-env:
        enabled: true
        type: configMap
        name: blocky-frontend
        advancedMounts:
          blocky-frontend:
            app:
              - path: "/srv/.env"
                readOnly: true
                subPath: env
              - path: "/app/.env"
                readOnly: true
                subPath: env
              - path: "/root/.env"
                readOnly: true
                subPath: env