apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-stefan
    namespace: cert-manager
type: Opaque
stringData:
    apiToken: ENC[AES256_GCM,data:bQPAUDyhpm850zIm2NI1/lDERYU7oxn8ETMrNLxlKpwnHGoBhsUTcA==,iv:0ZKo/qDG8j6d04M1tJOaSy2Qh8knnVy0QauCg78Bw7A=,tag:Xu0df2eUbvyVL3qSKVTPFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTmNjM0I4R1lxSnN6cERJ
            d3k4bmc1U3BIcE5hRnJXc1JUMENIYlBQYW1RCkVBN3NLZklodVpRUmtvd0FtbGNv
            c3NkMzJzRG0xSFZiRy9pUEpLRmdvRmcKLS0tIEVMd0hEb1N1U283Qi9WK2lscWRS
            U0toRUhTWFRrYzVnWWVPYkVka0JXOEkKVEuOPXsdSSJXQn0WWKXR8WaJ5lC5/FdD
            IvpPgTNUUUgchYC51DyThwabsN24+UEQs3FA3ABlszlFFXTkbi/3bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-06T12:59:45Z"
    mac: ENC[AES256_GCM,data:I7T02rL46zvuRkIBYJ7dGajJDLhELImeHNEhA8JmA7wWYHJAKB3+IzeF8A7+BB6D9wTk+db4Z0VL+9uggc5ec7OcUmrp/ycIfguN8BHZfMcWLAO4c9V+mpT0q2i8ChSjzujA9K8mjKrRQxv1nYkN7VNJzq7Ff5FyN6E7EJh3iCQ=,iv:NodbtxCwnjmOyrw8s19ZS0LVbv1wJB17SNv0OtQKYVQ=,tag:iro8O6+2r77mX1qch1+bOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
