---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-staging-stefan
spec:
  acme:
    email: stefan+cloudflare@schokker.dev
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-staging-stefan
    solvers:
      - dns01:
          cloudflare:
            email: stefan+cloudflare@schokker.dev
            apiTokenSecretRef:
              name: cloudflare-api-stefan
              key: apiToken
