---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-sonarr
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-longhorn
  path: ./kubernetes/apps/user/media/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
