---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: download-clients
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: slskd-configmap
    namespace: download-clients
    files:
      - slskd.yml=./resources/slskd.yml
generatorOptions:
  disableNameSuffixHash: true