---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-rancher
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-cert-manager
  path: ./kubernetes/cattle-system/rancher/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
