---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-immich
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-longhorn
    - name: cluster-apps-redis
  path: ./kubernetes/apps/user/immich/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
