---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: linuxserver/lidarr
      tag: version-1.4.5.3639
    strategy:
      type: Recreate
    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
      - name: TZ
        value: "Europe/Amsterdam"
    service:
      main:
        ports:
          http:
            port: 8686
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: lidarr.abchost.nl
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: lidarr
        mountPath: /config
      nfs-general:
        enabled: true
        type: nfs
        server: 192.168.2.210
        path: /mnt/MAIN/contain/storage/general
        mountPath: /mnt/general
