---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
            gpu.intel.com/device-id.0300-3e92.count: "1" # only gpu capable of hdr in my cluster so far
          securityContext:
            runAsUser: 101000
            runAsGroup: 101000
            fsGroup: 101000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 65542 # gladius:external-services

        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: "10.10.3"
            env:
              JELLYFIN_PublishedServerUrl: http://${CLUSTER_JELLYFIN_IP}:8096
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_DATA_DIR: /var/lib/jellyfin
              JELLYFIN_LOG_DIR: /var/lib/jellyfin/log
              JELLYFIN_CONFIG_DIR: /var/lib/jellyfin/config
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 120
                  periodSeconds: 60
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
                memory: 512Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 4Gi

    service:
      app:
        controller: jellyfin
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${CLUSTER_JELLYFIN_IP}
        ports:
          http:
            port: 8096
          dlna:
            port: 1900
            protocol: UDP
          discovery:
            port: 7359
            protocol: UDP


    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        className: "external"
        hosts:
          - host: jelly.abchost.nl
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: jellyfin
        advancedMounts:
          jellyfin:
            app:
              - path: /var/lib/jellyfin
      media:
        type: nfs
        server: "${LAN_TRUENAS_IP}"
        path: /mnt/MAIN/media/
        advancedMounts:
          jellyfin:
            app:
              - path: /mnt/general/
      music:
        type: nfs
        server: "${LAN_TRUENAS_IP}"
        path: /mnt/MAIN/miscellaneous/music
        globalMounts:
          - path: /mnt/general/music
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /transcode
                subPath: transcode