---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-internal-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: nginx-certificates
  path: ./kubernetes/ingress/nginx-controller/internal
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-cert-manager
  path: ./kubernetes/ingress/nginx-controller/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
