apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: immich
type: Opaque
stringData:
    REDIS_URL: ENC[AES256_GCM,data:kdlhh95y/Y749qE5lLx0bQ96MAKiURbzDWCtAb3p4x7bNqHGZUmyGoV/jpA8uBvbwHuqwjGDb8e88G7lXTka0spAqB3vXRDvIhGTQBEJlS2XaP2Aim6liwqzY+5KgberWr4Jt7M4KBya4i4ATZR0alUPyp4CEq+fIrSupBU7KyoaRMlRZ6+7vEt5R6RKKkn034kW0Rnye5xDbvme9x291f77Yxo5AKYm3WuwKsHqUG2C+smGe37//6zpDTRCE8mkjiuX3/RwYKeZ75Oe10ft90T/rQyYc9jefi0m/QzX3Wrc4+KBm8TxMmg94r1PGnVO+Ykik3261aikEdmg1K+s+EwbRyQ+pJBHUJdM6xjBZd29BRrzDMbYgsBnw2YBAhYfZMiLe9ltcQl7yJA7FACRqeUaDdidM9yrOp2b/6a9jWOyTJZfSCfufWSGsbEjSYiKbSK1NNm+D9SujyCa3hCTlOLd/X3X2PK7a1Vu/9wdBAVI453TxNgTa6j318kRN357bCGysBh1PaeiihRpxWPMYc3x7vM+PTgJCUOeNdb4Yqya2xlzA8u/IMaWE038ubDYQsLkhUhVkxwMmEBJ/ejVhzP61fJosRl47+ZEbaECEV1qdmRsn6d0/a7UgWC0DreYtcOTmbOPt6dpdGPymGIseusjXH7/9LGS13g8nAHpoV1ISYk/8yD8iluM3xxiLAkOcGrzmYNTjXstGUJteLfeHB7JDnaOVCeYuNrV4BHt7RN3vufhzdXoTTSh0UMwaUXesyS8I95bfj0+WDEVX+rAY3NPt7lHbHAjLL8/AHkCOXxUkVx+jwPfZA0NmpUsVA==,iv:1X4awGI5UMpbO8Z4czMQFt55iFmd1b/qHkTmiygFGJw=,tag:u4hKSyp9omhu5Rj0TIZ83g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V1JnUTlQZ2t1Vzg2MmR4
            UFl6WDNwaWkyM1M0SElrWjNUbVZ2TWlqZGxVCnJGR2xOdkZncmp4SEovbFR6ekRh
            YXorQzFncFhRQ3pLbHNINlRNMTBIUDgKLS0tIFdlWFgrdEZLUTVSakhjYnNyZ1Br
            Y2dZVTNIdUhuNG52cllHbmtRaEhWZXcKT8bx/OG9PrJO4f0xIF7kUHhcHiIIEi35
            b6vAK5tpGD8cCWoUFsdiKsIUE2jjKHA6NRK2173yaU/ah1mfdJRpDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-04T17:58:53Z"
    mac: ENC[AES256_GCM,data:o7xlBzKhcuqIF9uAcJGF50CX+O/IKV8q5BMAKZtJdH0hwh6kAENP3qgFAy+JYqW6ZTvh+wiT01MYLCjCkSZWAbnJZhz9s38Y1pqbB9sRUsN/hwv3TcvKiRYvfgPR2voounCrZdSw8ozrHmwAvsAqwqhI2VEGN+jgypm3/vcCSp4=,iv:Z86iE2dEHpmrhBSpn8TiFQqWePslWKMnz2RIPHa8dGo=,tag:yURCm7OxJqus7d+FKlmIXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
