apiVersion: v1
kind: ConfigMap
metadata:
    name: immich
    namespace: immich
data:
    IMMICH_SERVER_URL: http://immich-server:3001
    IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
    IMMICH_WEB_URL: http://immich-web:3000
    DB_HOSTNAME: immich-database
    DB_PORT: "5432"
    TZ: Europe/Amsterdam
