apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: immich
type: Opaque
stringData:
    REDIS_URL: ENC[AES256_GCM,data:BJn6LbK09ZpnzbDeVbS6fOs3PVBoskZQedLkN5miogEPBiSVM5+c3iEF6enNjcj5U6YVgwAXpVEt4Ntb68zzt6dkS62B+Ho+JCcnIoGOx6qK1diXMwS/3m7ZwbBlu3X2cHlP3ZY/gI3qZke446LNumZjbJUf8+UT5xFp+GS0EmEFIH4EUN26e3Z0XV7aBncd7fNd9Nx8NuKDBFixzaxVG25Jyd5fEoqhNIaMDQ5ENg9ewbuJaXd2+e7m0VqHFdQsgtN0pp91cTsxVJuQWI4SUk+m8Rvpk5IljFth7B7UyxYe+xIl1UsdDOO4ytsiYfjJeLS/Llr+JHDUzwyLwBNsZcoHEsnZkNwQvb1npJONfHFN06XKeOqLf2fO9uWrDcwFa6Y+nBipMAT9XA8ZD+wgmaUxyNOS7EtofcahDoxPJKcQjJA9b2xvZpIPfmrkp7vSXAMdlrUase7aL4OWD3ucr3M9Ci1my3gF16Qdw6AD4L/cIpCJM3yOwaSq,iv:dTIYE/04TPd282bYNg8EdpLc387vgMyp1gMYOofLH4M=,tag:Vg2HdTZhEsMHcRMAkD7pdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V1JnUTlQZ2t1Vzg2MmR4
            UFl6WDNwaWkyM1M0SElrWjNUbVZ2TWlqZGxVCnJGR2xOdkZncmp4SEovbFR6ekRh
            YXorQzFncFhRQ3pLbHNINlRNMTBIUDgKLS0tIFdlWFgrdEZLUTVSakhjYnNyZ1Br
            Y2dZVTNIdUhuNG52cllHbmtRaEhWZXcKT8bx/OG9PrJO4f0xIF7kUHhcHiIIEi35
            b6vAK5tpGD8cCWoUFsdiKsIUE2jjKHA6NRK2173yaU/ah1mfdJRpDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-03T22:58:18Z"
    mac: ENC[AES256_GCM,data:v2V5wxHZxL4NWIPybAZIqR2bWTD2PfDbBMywBmACbIMtg/Q3JPpZuYc2wHamKxj9PGFaZa8Z0SS2kNrn30AfhtQGnzN00oUxVvIuG/ZjEXbGoKO6bvnHo0FwZz9AyblJgn0FAU1TaNQmsvzujj16IaNU2bjwHLBfbu9aCYbaKZA=,iv:GOZhH18bwEjBSbUXqLJGCDbyEQR6HXgSHve7ewz0b3Y=,tag:Kq3S7kK28H5QAqDc+zeN9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
