apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: immich
type: Opaque
stringData:
    REDIS_URL: ENC[AES256_GCM,data:CdYs4sSY7vnWeYqb3c9mzsCrCw4bS7sKlQIapYL/v8Nmw9Ys0Nn55FGfvyKVbLUJx/2R1fo+vDU6ht6wNzIvDE3E/eB1Bhjyik2GjMJ3s69tO6tCS5IAAabBeWgDfljVnaX9KMWHm/MCWeO9WfrIKGZpw13YSpStA2lkXTFvQUh9wq1rWmZpO6nD+/4pJo32zGp7dfeApAVOhr2x6pzreigPPWQq3RP7eZvvrMHvW4NWkzh2YwkMCV07TyxP103IqJW8p6eh8XBfqwAYasVvk4nynFt4IDSKTamz/BDJLcBD9DHo5wP6v7wv8adI2X0Ndi8l3YL8SgIVHKPsTGvsQwOwLCQkOUoktq8O5E0gBN47Leo6vuxNMVV576MQVUGL9qqRiJTqqpfZaOG5uMiwp6DKCVveolrSWXpcTxarSpv0qsdtBo12RuUxhqUdP4wQy3urwaTkQUgeefg23PF2GxhHNa3LWzup71cQKcTxIZ7yfhm/1cPuxz1N0r8YR64ooqp//VoDBqKuFQb40Hb8VoLzHbaTrEwe8L9CEgPbQp3r1A9vP9x+4EZ/xAme4+FaKbGAf5s3EzaKzDtb6AvR4Kp0sVm9m1jEfIUU2jemdlDjTH+q0ZK0sTlEPOBMG+oFdbJAbH1rybS1tWoLpD0h3pcpGrSms3lFeoqgMtmuxgzTf3oGNsBDxlTG1nkcAUbr6ImndFc4DXSvqJNlZ6wSHGffFtQEJjrRF9zjhMO/JjoPMpMtZ4E30xnzraSlDEb+gzOS6pXRIFHcAmsAQ2s4dCJzF8pNZmw7DLaujvM592Fb4pZv8TsZVVF72LexlmhnICOCNyTe/Tof2MV7xQANLSTvgpA9eVZq+bXZxdPgdpymSNocw8g=,iv:UkcKhlVsxkiZql2xAGDu0z9etimn1QIg0mZaNaQoXC0=,tag:1cWLgJYdaM5rVsCtvQYHSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwemdSRVlEK01FalNnT2tN
            T2QzK2dPTVFaRnliT2hjWHh0bmxxTm0zUkRBClh2ZUxSeU43OTAvZndyVmFhVHdr
            a3c2Wm1WM1dqbFdFTEI2WUQwd0FVcXMKLS0tIE9XcDUydElXYlgwU09MK0ZVZWQ3
            c2x0VSsrZFFtZm4vRVBKei9sWStUeTQKgUUbshtAbsiyi6CnoOTejPGnFUuHZWVW
            HC6bx9a51e4DE13WPSSJkxSTpvASfjRuNoVu1aeyT2B0E7UueX3+HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T19:33:20Z"
    mac: ENC[AES256_GCM,data:TWr/hXV2dw2dErm2xDtsMqzHbsbg6lvbU+GBCY83f2oDcTsdvBef+eQB5TBUvXja0LxhCBzkJlqt3D5cMpx03oOqmKKFtzo0ZZb7tv5wqCT3ehuMEvcFBKUnYyBzR1sXmT5fAvcKwKyufv0ONINnZycD7P7eY1rh1jLNphqiSIg=,iv:5Nbje9kyDfxEMgZvwGGFhCPhHyNb9N8C3h3I/vwit4A=,tag:fF66ug4cOdnJrSZa6e8cTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
