---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ./immich-configmap.yaml
  - ./immich-secret.sops.yaml
  - ./postgres-secret.sops.yaml
  - ./helmrelease.yaml
