apiVersion: v1
kind: Secret
metadata:
    name: immich-database
    namespace: immich
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:NdzxqgcS,iv:uIwbUWKe7BVTxCu6FMSGTO2VNdD+tBQlmXPw8LSayAA=,tag:8lEvWlxgD3HdwkvLF/tnOQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:cYI0eXf4WgwzSDswhquvbt85SfrP943cvDKJ5MelswU=,iv:zKvg1WWW8aJA3IzYg/fXPv8e9awMFZwCdBh1IfxRBSk=,tag:/18PbPxb+niILTOgstcggg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:QeCtLYNe,iv:IgmfBV0j3l+qgDTwRauarN4bj9a+buS4+bzxxT32sjQ=,tag:dgIPYUPUldhjKHOKXVyg+A==,type:str]
    POSTGRES_URL: ENC[AES256_GCM,data:ewu4ulfoJBBqeWL2VzmjxoZk1N7/APWs1i4KqU0EbqekWbk914x700YmsHopFWGzuDq1auBR9XezMmW+qwE0Vwj7b43uyoc+64Cmnchm/vPKYMm3lsns,iv:OZ/EHDivskR+zn1aZnuan1u6HZnQL/SozA9XayGGHcE=,tag:91+Hrh35mv32iIZjCry+1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcGhEcmpTaDVtNXR0SmxT
            V1hwRzdCdWFkbW9TWTYzZ1Q0WnZrMVdXQW5BCndmVGVVUFMvNDdHYnJxTUI0UFBw
            S1NJd00raDVVdkZCMHNOemR3TTlsMlkKLS0tIDNtZk1yOFJaYjdtZlRuV29hWXZx
            TkZ1K0ZETjdwMUdXNkpzQ1BobkhKbFUKq1Jw5/pE7+iMMfd+0FGNQbJDACCs7qKi
            n58gryjXxc6DPdYqcGgQpFBwYCFQMR/nHrZAvdAcu2sX1RdjHY/Q7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T13:42:06Z"
    mac: ENC[AES256_GCM,data:3xQYceS8TweoLdjgf4bMVd0lSjwX1IRZ5q1OvkZUut6jkCysgeGhuC1AV7ZxPzFxkvtwCkWC8HiBgj6hjBiloOZD3SN54TtDRNW8N84lZMha4CO/ItM4ZInFNN4+U3tA/VbXK/lUZ6+KxdjmbBKj32rNvaLMeVypiBv4kHbMU7Q=,iv:8VOAMkxxpnCmoRSz1sJE9YygVEO953emrcr/04MaxFU=,tag:AEm4kpH+bGlByfynSfFIQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
