apiVersion: v1
kind: Secret
metadata:
    name: immich-database
    namespace: immich
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:NdzxqgcS,iv:uIwbUWKe7BVTxCu6FMSGTO2VNdD+tBQlmXPw8LSayAA=,tag:8lEvWlxgD3HdwkvLF/tnOQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/Pa1jp7njsFm//X1K2M+6PnQ1UnZohlGiWtxiojZM5u+XeFU5LrWRzlP5d+mnNtYP/Mi7PZsE4/V+1pxaf3Q0A==,iv:wuXWELEcCB2Ec01dp0NRz2C2KwQpIBETdPmvSzGrTIo=,tag:oHMT9OTQ46pBvwrNpeFYuw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:vU7PMQOFjGOc,iv:bjFRhXgRXhdSOChNiyW+iNoQPiCMz4DYH7pyIEj3GM8=,tag:UGUEqH0BcFBe7tvbU0+K5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcGhEcmpTaDVtNXR0SmxT
            V1hwRzdCdWFkbW9TWTYzZ1Q0WnZrMVdXQW5BCndmVGVVUFMvNDdHYnJxTUI0UFBw
            S1NJd00raDVVdkZCMHNOemR3TTlsMlkKLS0tIDNtZk1yOFJaYjdtZlRuV29hWXZx
            TkZ1K0ZETjdwMUdXNkpzQ1BobkhKbFUKq1Jw5/pE7+iMMfd+0FGNQbJDACCs7qKi
            n58gryjXxc6DPdYqcGgQpFBwYCFQMR/nHrZAvdAcu2sX1RdjHY/Q7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-02T17:58:01Z"
    mac: ENC[AES256_GCM,data:WAwXpIHZpu/cc7y0sfMIEt37777EC+0S3GWERH/vuVuuRuaqGS3Q2SujXK1sq0NmEvdXnOB8Pfn7fkj80WCjD4B5Lw/zh59YXYydDSXZbjpKCteQKttEefQNhRXZfIBycDO/9F2bs6LuhFdShyg/hhTzcN/gU/Hg42j6gJbcGzQ=,iv:PBLqVjzyYhF219ezajlJ1UfRE+ugAEEh7Kek+VU7w2c=,tag:fumIXDjZgpNVgccHwAjsoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
