apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: immich
type: Opaque
stringData:
    REDIS_URL: ENC[AES256_GCM,data:KbqxN1gFqWQvrOY+Bd5FKeUr13Ts1CYyvHPvYgm+V1bXKXiKvKTfQzoc5KMe/LbGBS1M13QEKw24l60GwaYk944h5+xCfzThfK5YjAqQPigepMdWC144PWITpGBZWdzhlKd3r+Jf2RiZY9bfSoV8PnJmQxtEYpRB+VtTHhmXM/ojbhdZbIrlkDyQQzRjbfR9EBRRqhUSINGlbh55Loy4FwON8CfqiVk1a/ncisElBV7sHX9QLSfHqMQJKNAwRr7AqGdpZEpb/FYu0hsd6fbLMjxWjWuc9MfNXUwHcAG9qhtJsK7EdiTv67zRKPn/xgrGo5sYjVBhZIM4xJPO5gsEqY1Kp0KazEHF7Qwga0r16l4F7ONG94XS+gzEQ1GXMnp7ODaAjIc5hYMg2Y8CUOaIknrJTyYiVhw6Dqg8y/UIu4NYvGKjmVcGqP2PZWlOlBmDatEsMzB5UQcqheWTliLX45YoREJ1VCw/qNx6BkZt6u+fyuxa0vu95vXC2alRwXjWfGRoF94IH2SUHEa/cVBGWCxHvo6TjdRlzgJeBfXfqMaoz+oYQCYzc2HFkwCgRzB6zO0BHBpm17VknnYiT44X4MDcqUIuQMmpAAbIEHbwlS4HctwV3Rtzcoa0/2sW5pjTw3kEOFOPXUJPVa+0DJaiydgjJ6tltShueWjCkJH4GJwRcA/muIJTLlmxpbi1BGNMcg7vQFtFt/vJQlLMNPy2Vd7pooVvpBoPlQ+Z8eWTgps2v0x6JI6UoqCFbflIcW93tpz6MFwUJ87Rwi/69X/aqwnfAlcfw2hZDwxtKSzLWaY=,iv:qTrpQK1RbmIGes6hkt4X0NbzEF98tf7dwppcxmHASHU=,tag:XwRe3x3vxmkX76oQw0Z9lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNHdSSzFtbGNZMUxobjBH
            Z2RvalVONGNoR05DYThzeXhlbVpzMW01Q3kwCmpzVUdGUFBKZ2sxL3lGNFQ5YjJT
            Z1YvcmxFcyt3TDNBbVdWd1FOOUFhaDQKLS0tIElsWDZkOXdVNlJsczZGR0ZZTTlL
            RzlrRGQ3dmthY1FDcEhjQi9kaS9HQzQKEoYP/Zc/gLfg2n2o9osJChnRlK4dNWKa
            Qie3M43mEHwxrH0grCIx9x7aEMsdaZxPmg/pBHK0YPhg/eYsErl8CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-02T22:07:46Z"
    mac: ENC[AES256_GCM,data:bIRQkiTAEPF24dIyF5HBWVPCNvdxguag2Kxp8fCUTVi+ucXfjSSfkCjZRXzP0592wZif4Fvm1oNOP9YKn5+nukuMSKOvFuQo28Hz64n1r4PGcbhzy1PRpJKA03SnQuZVFaE/UYued+OgsTEmUEFAMCEHTuOrCfQK/L2lmeXhTWs=,iv:WfhkNoFHMPKxK48C1GkwmrPZ27+ShMSe5GsErQhOmbg=,tag:0z1enBQ24VPZVTTHL1L4/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
