apiVersion: v1
kind: Secret
metadata:
    name: swetrix-secret
    namespace: web-hosting
type: Opaque
stringData:
  EMAIL: est@test.com	Email address to use for access to dashboard
  PASSWORD: 2345678	Password to use for access to dashboard
  JWT_ACCESS_TOKEN_SECRET: wt-access-token-secret	Secret for JWT access tokens
  JWT_REFRESH_TOKEN_SECRET: wt-refresh-token-secret	Secret for JWT refresh tokens
  API_ORIGINS: A list of allowed origins (for the Access-Control-Allow-Origin header)
  REDIS_HOST: redis.database
  REDIS_PASSWORD: password	Redis password
  REDIS_PORT: 379	Redis port
  REDIS_USER: efault	Redis user
  # CLICKHOUSE_DATABASE: nalytics	ClickHouse database
  # CLICKHOUSE_USER: efault	ClickHouse user
  # CLICKHOUSE_PORT: 123	ClickHouse port
  # CLICKHOUSE_PASSWORD: ClickHouse password
