apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: home
type: Opaque
stringData:
    mosquitto_pwd: ENC[AES256_GCM,data:JDxFJfNhCu07zljruBdQv+25Ui7GFPLfM/C/2Kmklw7vfaCMH04FrmQen8w=,iv:auLDatM44QaTc2Yb6Df4NLKDyjf4WrnFn7B6H6PGjUk=,tag:RyXIhkl5z3rb2yrnxAh/cQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaThZbzR2WDFLcUI5Qmls
            V1JvanNNNDA1MzVyRUt5bWw0L051Zzg4VGdJCkpOSm4rL3lwajl2VGNOL0IrZThG
            dGdnUXlNQkdnN0RiSml4Skt5S0lvc2sKLS0tIFo2R0F3L1BpeEdDZDRzMlkrVXBl
            TkR1c25mNk1oK3RDUVR4Vkp3U0JmcG8KAv/C45bpBsTTzp46rz3BjxU4wy1J9wNY
            zEmT/DSMokGoT1QiIjdM08hyMWqT9hHzyP6RyFtwjrEjo6lO0Mrt4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T14:40:43Z"
    mac: ENC[AES256_GCM,data:cbVLxtYWALX9cOSpB1KBgJlNEKydT7ybvK6uqxYnzbtpAuNaqYrdnvRyTR/cF8xBWLQjFR0JDmvtRQmFk9nnNy/uiCFeg0QBH1lkRIx7iLzzQGhkALl9PtiJSi65HSwKUxuWBoCVI6L4WzOEOgP6/lOY9q5tiDicqjlGe99SfEc=,iv:vu5PW3xV6VWRmPWoRXhFS6xC4empo1CE9GqH1ddXSfk=,tag:J4mt3nUEd5b6/9Uguygw2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
