---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: user-apps-mealie
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-longhorn
    - name: cluster-apps-cloudnative-pg-cluster16
  path: ./kubernetes/apps/user/utilities/mealie/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m