---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: linuxserver/radarr
      tag: version-4.4.4.7068
    strategy:
      type: Recreate
    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
      - name: TZ
        value: "Europe/Amsterdam"
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-internal
        hosts:
          - host: radarr.abrondijk.com
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: radarr
        mountPath: /config
      nfs-movies:
        enabled: true
        type: nfs
        server: truenas.abrondijk.com
        path: /mnt/main/media_library/movies
        mountPath: /movies
      nfs-downloads:
        enabled: true
        type: nfs
        server: truenas.abrondijk.com
        path: /mnt/main/media_library/downloads
        mountPath: /downloads
