---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: linuxserver/bazarr
      tag: 1.4.0
    strategy:
      type: Recreate
    env:
      - name: PUID
        value: "101000"
      - name: PGID
        value: "101000"
      - name: TZ
        value: "Europe/Amsterdam"
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/prowlarr/hotpink.css"></head>';
            sub_filter_once on;
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: bazarr.abchost.nl
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: bazarr
        mountPath: /config
      nfs-general:
        enabled: true
        type: nfs
        server: 192.168.2.210
        path: /mnt/MAIN/contain/storage/general
        mountPath: /mnt/general
