apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
    namespace: media
type: Opaque
stringData:
    BAZARR__API_KEY: ENC[AES256_GCM,data:WFI0v4KrbFy02+eUVTSEqUWhlMr+rbr+zG+KgLQBFSc=,iv:gj/xU8v/K9GCYMV2CZemGhMj30KkxyWeiOQuP+og3mE=,tag:H4G4Mx+0F3CuVB0Jgq9NFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsY3lubmVlR2k4Y3N4NnpJ
            eElMd0MybXVJN2ZpUW13cGxPaFIzdnhBNGx3CmxtL0QwRDJQSHlicDV0NEt3ajkr
            SVA5NTZiTVVpc0tYMDFYdGhpWCtFNmMKLS0tIFgydE5TMjVjdzJ4T3J1ZlcxSjgz
            RVJnbTJFcEU2MTArdnJiRHZVblVwOUUK+UpY6C8jIZ5vyWWuDiYB9RQNJ6DsCZUR
            nPFw7ShrqGdf1Ar2OAUYvcpNpMCmCek6Z8PegXGOko9eGaiOrTIL4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-19T21:54:48Z"
    mac: ENC[AES256_GCM,data:YwYQuJea6r/zOb8CAvNPeqTbdec209xofbAQkFmQpORg5NWs3UdH5DHNEpaGIq77zyVE+wvJ9svhyOK9pd8g/E3UDTrm8ZuWUchi5eILRgBLwPxEYk8fXiLXW0dsDBA7mt8zUNIDGV4g3XoJieo3OJw2stAjGQ6KRqAEFqs3AS8=,iv:zZ2BkOXD2o9kKZii8VZhc3ZRt/YmXlWKkWQmbTDmovE=,tag:mG1OoeCGnOJXTKlrx88S0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
