---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-plex
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-longhorn
    - name: apps-intel-device-plugins-gpu
  path: ./kubernetes/media/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
