---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: vpn
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: linuxserver/prowlarr
      tag: 1.7.4
    strategy:
      type: Recreate
    env:
    - name: PUID
      value: 1000
    - name: PGID
      value: 1000
    service:
      main:
        type: LoadBalancer
        externalIPs: ["192.168.4.101"]
        ports:
          http:
            targetPort: 9696
            port: 80
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: prowlarr
        mountPath: /config
