---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: invoice-ninja
spec:
  interval: 1m
  chart:
    spec:
      chart: invoiceninja
      version: 0.10.2
      sourceRef:
        kind: HelmRepository
        name: invoice-ninja
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 0
  upgrade:
    remediation:
      retries: 0
  values:
    debug: false
    image:
      registry: docker.io
      repository: invoiceninja/invoiceninja
      tag: 5.11.6@sha256:257ef86b2e2127f5b3dba787dca453d4d6ea9a79555c87b83bddb9398ccc5af2
    existingSecret: &ninja-secret invoice-ninja-secret
    updateStrategy:
      type: Recreate
    nodeSelector:
      kubernetes.io/arch: amd64
    mariadb:
      enabled: false
    externalDatabase:
      host: "invoice-ninja-mariadb.infinigon"
      user: invoice-ninja
      database: invoice-ninja
      port: 3306
      existingSecret: invoice-ninja-db-secret
    redis:
      enabled: false
    externalRedis:
      host: dragonfly.database.svc.cluster.local
      port: 6379
      sentinel: true
      existingSecret: *ninja-secret
      database:
        default: "69"
        cache: "70"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 512Mi
    # containerSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1500
    #   runAsGroup: 1500
    #   capabilities:
    #     drop:
    #     - ALL
    http:
      image:
        repository: bitnami/nginx
        tag: 1.22.1-debian-11-r21
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 512Mi
    persistence:
      public:
        existingClaim: invoice-ninja-public
      storage:
        existingClaim: invoice-ninja-storage
    ingress:
      hostname: &host "invoice.abchost.nl"
      ingressClassName: internal
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 100M
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
        nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
