apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: utilities
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:2kg5BUjcTlxd4bM/HGvYPFXZuL0GOoRWZa1tHP2GCpYfxQe0iOwBs0b5wbdbI7wryZxuYlpa6rah8hD62mzDZA==,iv:kLXtpMeGsV64E/IQdB7F58x3KproTxRvLMPY2iDuJkE=,tag:x1kwoGXYwLJqFy6csTLcnA==,type:str]
    YUBICO_CLIENT_ID: ENC[AES256_GCM,data:qMvjZh4=,iv:hhjL7p9WmFf1uUAB3hnSB7wKva9DUexWkURnfdpXhxY=,tag:3y5s0ILTJtvpQEIGO/aRcQ==,type:str]
    YUBICO_SECRET_KEY: ENC[AES256_GCM,data:3fF2zXIHaLcONwl0yM8IBuNOe8aDIvxfCG9iBQ==,iv:YZ89RjR5bt/oCFd1bOXHAfs17TVJhMRd0/793UfK5ls=,tag:U2BFaIEGmg+Dq9Zw5+RAiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMHpOc2JYUDJsZDZ3SEp1
            QnQ1ZjE5eVhjRjJwRVZBaEZIOFMwZUJkTEU4Cjk4UlZPT2M5NU9QS3IwTWt1RHVG
            MlM3eEEwRFg2bkpWc2NFdDFKNWh2bEUKLS0tIEdDZWlaYmVycnpKTVFqQTBmN1ZD
            S21JaU4rUUFRdUhFQ1FHV2dBSXQ2d28KYOvBEx0R/W4Wk7IcbI7ElbnSYuQnft4w
            2jjTqJwpbO97HqHFz2HmvCeNcjpRXxBwUb8zUa/8u7GdnUwJO3ihCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-08T17:19:48Z"
    mac: ENC[AES256_GCM,data:k5spx/wpmZ9Ae4HUs2Zf8q7Gc4ZqOQoYdrd5G2z+oHKR9KkSYyGR3r0StwlXLo/lAvabLnkM/GMgpEehF34cV9DSCe7z/q2lLL1uq7R/w9CJk4V6mV+PjbAvvjRG5D5TWJX2a/t/DztlkX2aKFtXdZkBNfissP0yqtDlGq2zAPs=,iv:1H4g2yfKcP09KThRwGUi3fU6qYuRr+AdeiLYcS+BQzA=,tag:dG3K11YJ4aeR3KD7Vw95HA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
