---
apiVersion: v1
kind: Service
metadata:
  name: postgres17-lb
  namespace: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres17.abchost.nl
    metallb.io/loadBalancerIPs: ${CLUSTER_CLOUDNATIVE_PG_17_IP}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres17
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: postgres17
    role: primary
