---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: download-clients
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/home-operations/qbittorrent
      tag: 5.1.2@sha256:9dd0164cc23e9c937e0af27fd7c3f627d1df30c182cf62ed34d3f129c55dc0e8
    strategy:
      type: Recreate
    env:
      - name: PUID
        value: "101000"
      - name: PGID
        value: "101000"
      - name: UMASK
        value: "002"
      - name: TZ
        value: "Europe/Amsterdam"
      - QBT_WEBUI_PORT: &port 80
      - QBT_TORRENTING_PORT: &torrentPort 34977
    service:
      main:
        ports:
          http:
            port: *port
      torrent-forward:
        type: LoadBalancer
        ports:
          qbittorrent:
            protocol: TCP
            port: *torrentPort
            targetPort: *torrentPort
        status:
          loadBalancerIP:
            ingress:
              - ip: "${CLUSTER_QBITTORRENT_IP}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: torrent.abchost.nl
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: qbittorrent
        mountPath: /config
      nfs-general:
        enabled: true
        type: nfs
        server: "${LAN_TRUENAS_IP}"
        path: /mnt/MAIN/media
        mountPath: /mnt/general
