---
ports:
  dns: 53
  tls: 853
  http: 4000
upstreams:
  strategy: strict
  groups:
    default:
      - 1.1.1.1
      - 1.0.0.1
customDNS:
  customTTL: 1h
  filterUnmappedTypes: true
  mapping:
    bw.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    bazarr.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    dns.abchost.nl: "${CLUSTER_BLOCKY_IP}"
    home.abchost.nl: "${CLUSTER_EXTERNAL_INGRESS_IP}"
    idrac.lan: "192.168.2.126"
    immich.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    jelly.abchost.nl: "${LAN_NUC}"
    lidarr.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    longhorn.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    marax.lan: "192.168.2.205"
    mosquitto.abchost.nl: "${CLUSTER_MOSQUITTO_IP}"
    next.abchost.nl: "${LAN_NUC}"
    pgadmin.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    postgres.abchost.nl: "${CLUSTER_CLOUDNATIVE_PG_IP}"
    printer.lan: "192.168.2.200"
    prowlarr.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    proxies.abchost.nl: "${LAN_NUC}"
    ptu.abchost.nl: "${LAN_NUC}"
    radarr.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    rancher.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    schokker.dev: "${LAN_NUC}"
    sh.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    sonarr.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    tdarr.abchost.nl: "${LAN_TDARR_IP}"
    torrent.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"
    truenas.abchost.nl: "${LAN_TRUENAS_IP}"
    un.abchost.nl: "${LAN_NUC}"
    univac.lan: "${LAN_NUC}"
    zigbee.abchost.nl: "${CLUSTER_INTERNAL_INGRESS_IP}"

caching:
  cacheTimeNegative: -1
blocking:
  blackLists:
    ads:
      - https://big.oisd.nl/domainswild
      - https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list
      - https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt
    trackers:
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/alexa
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/apple
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/samsung
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/windows
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/huawei
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/xiaomi
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/sonos
      - https://raw.githubusercontent.com/mullvad/dns-blocklists/main/files/tracker
  whiteLists:
    ads:
      - https://raw.githubusercontent.com/mmotti/pihole-regex/master/whitelist.list
  clientGroupsBlock:
    default:
      - ads
      - trackers
# redis:
#   required: true
#   address: redis-master
#   database: ${REDIS_BLOCKY_DB}
#   password: { { .REDIS_PASS } }
#   sentinelAddresses:
#     - redis-node-0.redis-headless.database:26379
#     - redis-node-1.redis-headless.database:26379
#     - redis-node-2.redis-headless.database:26379
