---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-server
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: immich-database
      namespace: immich
    - name: redis
      namespace: database
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.105.1
    args: ["start-server.sh"]
    strategy:
      type: Recreate
    envFrom:
      - secretRef:
          name: immich
      - configMapRef:
          name: immich
    env:
      - name: DB_DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: immich-database
            key: POSTGRES_DB
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: immich-database
            key: POSTGRES_USER
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: immich-database
            key: POSTGRES_PASSWORD
      - name: PUID
        value: 1000
      - name: PGID
        value: 1000
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: immich.abchost.nl
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: immich-server
                  port: 3001
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    persistence:
      library:
        enabled: true
        type: nfs
        server: 192.168.2.210
        path: /mnt/MAIN/contain/storage/general/immich/library
        mountPath: /usr/src/app/upload/library
      thumbnail:
        enabled: true
        type: pvc
        existingClaim: immich-thumbs
        mountPath: /usr/src/app/upload/thumbs
      encoded-video:
        enabled: true
        type: nfs
        server: 192.168.2.210
        path: /mnt/MAIN/contain/storage/general/immich/encoded-videos
        mountPath: /usr/src/app/upload/encoded-video
      profile:
        enabled: true
        type: pvc
        existingClaim: immich-profile
        mountPath: /usr/src/app/upload/profile
      upload:
        enabled: true
        type: pvc
        existingClaim: immich-upload
        mountPath: /usr/src/app/upload/upload
