---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring-system
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: louislam/uptime-kuma
      tag: 1.23.15
    strategy:
      type: Recreate
    env:
      UPTIME_KUMA_PORT: "3001"
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: status.abchost.nl
            paths:
              - path: /
                pathType: Prefix
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          exec:
            command:
              - node
              - extra/healthcheck.js
          initialDelaySeconds: 180
          periodSeconds: 60
          timeoutSeconds: 30
      readiness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /
            port: 3001
            scheme: HTTP
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: uptime-kuma
        mountPath: /app/data
