---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-dragonfly-operator
  namespace: flux-system
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app dragonfly-operator
  path: ./kubernetes/apps/database/dragonfly/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  wait: true
  interval: 10m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-dragonfly-cluster
  namespace: flux-system
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app dragonfly-cluster
  path: ./kubernetes/apps/database/dragonfly/cluster
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  # dependsOn:
  #   - name: cluster-apps-dragonfly-operator
  prune: true
  wait: false
  interval: 10m