---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.24
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      main:
        controller: main
        ports:
          http:
            port: 4000
      dns:
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${CLUSTER_BLOCKY_IP}"
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP
    persistence:
      config:
        type: configMap
        name: blocky-config
        globalMounts:
          - path: /app/config.yml
            subPath: config.yml
            readOnly: true
    # configMaps:
    #   config:
    #     enabled: true
    #     data:
    #       config.yml: |
    #         ports:
    #           dns: 53
    #           http: 4000
    #         upstreams:
    #           strategy: strict
    #           groups:
    #             default:
    #               - 1.1.1.1
    #               - 1.0.0.1
    #         customDNS:
    #           customTTL: 1h
    #           filterUnmappedTypes: true
    #           mapping:
    #             dns.abchost.nl: "${CLUSTER_BLOCKY_IP}"
    #         caching:
    #           cacheTimeNegative: -1
    #         blocking:
    #           blackLists:
    #             ads:
    #               - https://big.oisd.nl/domainswild
    #               - https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list
    #               - https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt
    #               - https://v.firebog.net/hosts/AdguardDNS.txt
    #               - https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt
    #             trackers:
    #               - https://v.firebog.net/hosts/Easyprivacy.txt
    #               - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    #               - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/alexa
    #               - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/apple
    #               - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/samsung
    #               - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/windows
    #               - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/huawei
    #               - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/xiaomi
    #               - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/sonos
    #               - https://raw.githubusercontent.com/mullvad/dns-blocklists/main/files/tracker
    #           whiteLists:
    #             ads:
    #               - https://raw.githubusercontent.com/mmotti/pihole-regex/master/whitelist.list
    #           clientGroupsBlock:
    #             default:
    #               - ads
    #               - trackers

