---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.24
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                - NET_BIND_SERVICE
                drop:
                - ALL
              readOnlyRootFilesystem: true
          ui:
            image:
              repository: ghcr.io/mozart409/blocky-frontend
              tag: v0.2.1
            env:
              - name: API_URL
                value: "http://{{ .Release.Name }}.networking:4000"
        statefulset:
          podManagementPolicy: Parallel
        type: statefulset
    service:
      dns:
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${CLUSTER_BLOCKY_IP}"
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP
          dns-tls-tcp:
            port: 853
            protocol: TCP
          dns-tls-udp:
            port: 853
            protocol: UDP
          http:
            port: 4000
          ui:
            enabled: true
            port: 8002
            protocol: TCP
            targetPort: 8002
    ingress:
      dns:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.abchost.nl"
            paths:
              - path: /
                service:
                  identifier: dns
                  port: ui
                pathType: Prefix
        tls:
          - hosts:
              - *host
    serviceMonitor:
      main:
        enabled: true
        serviceName: blocky
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 30s
            scrapeTimeout: 10s
    persistence:
      config:
        type: configMap
        name: blocky-config
        globalMounts:
        - path: /app/config.yml
          subPath: config.yml




