apiVersion: v1
kind: Secret
metadata:
    name: blocky-secret-test
    namespace: networking
stringData:
    REDIS_PASS: ENC[AES256_GCM,data:47MM3wpeaajm9NowNOVUEvPksDHJp3qG8UkdqPdZfgmLsXut7pJoa6hKaGUrXiDMdYVTkOnxC+0SarfkdZDVWA==,iv:gowpMPPOtLU3/McrbglAylznHRixDdxpiqxBUz0fDJ4=,tag:rURpGGdbIBJtHNjBL+D7Ng==,type:str]
spec:
    target:
        name: blocky-secret-test-configmap
        template:
            templateFrom:
                - configMap:
                    name: blocky-config-tpl
                    items:
                        - key: config.yml
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbUxuVXVoMnJoQjlpMmxn
            YlRCOUo4UU5tKzAvSjR2ZXJjYnRPd1Z1WTM4Ck9QRVo5TFpGL2tacFl2RFVXZk5E
            R0dFbUpKSXlqQm1zUnRXUHB4S0ErbGsKLS0tIGUrNFZXRGtUR3dpTTdDWjQvZWlq
            c2ptVW0yRXpJNXpBWWpPT1ZWS0pCdU0KJmZ1nLbIt/D1SU+RvgB/vXPSEhf4nW9k
            2I/My1EEzG8yMbzy02y2Z8DpJNrZQWcDOV+wdok/t9EWC6iyt8LYoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-28T16:05:10Z"
    mac: ENC[AES256_GCM,data:QKYRvlMGAAH10OalRGYN2GO/miPmWVMec9l2gDTwZpZsyzec0Y6u1FtZ1aJg8BFjKtsrNH6YfX0CG6TT6c0Yxh0p2MArnoXdS71id1qEYbwLHQB+nil3DUWcXlNn/OybaAePAUymuO+cS2Q2NXFbRJqsS9qkMzA1s/LZMGdLQ9w=,iv:70C3kpZ8I4qTx78/boMnaZXbvjwWVhBpwBozJ/UCcnM=,tag:IMnI5JqV+FS/sAb6LEueDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
