---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
  namespace: utilities
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v2.7.0
            env:
              TZ: ${TIMEZONE}
              BASE_URL: &url https://meals.abchost.nl
              PUID: 65534
              PGID: 65534
              AUTO_BACKUP_ENABLED: false
              ALLOW_SIGNUP: false
              DB_ENGINE: postgres
              POSTGRES_SERVER: "postgres16-rw.database.svc.cluster.local"
              POSTGRES_PORT: 5432
              POSTGRES_DB: mealie
              OIDC_AUTH_ENABLED: true
              OIDC_SIGNUP_ENABLED: true
              OIDC_AUTO_REDIRECT: true
              OIDC_ADMIN_GROUP: mealie-admins
              OIDC_USER_GROUP: mealie-users
              OIDC_REMEMBER_ME: true
            envFrom:
              - secretRef:
                  name: mealie-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: 9000
    ingress:
      app:
        className: external
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: meals.abchost.nl
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: mealie
        globalMounts:
          - path: /app/data
      tmp:
        type: emptyDir