# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mealie-secret
    namespace: utilities
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:1L5h6r4/,iv:kvrHVg/gKf0p9puAZGf2QfsVOvVEqa9kbnNamgOY1BU=,tag:cP2k2aFb63ukubShgf7LqQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:jr/YV9mhEzgQ7HuUbwOUPSn80s4KsXhjUXa/nrzBbiWayFQK7fL4+D5aMEfP4JXZ04/rzk/nuLjM8YrPSHO15w==,iv:VjnPptm4z+yJLSdKy9H+vC4hKCal2g2gc0A61t7rbwQ=,tag:2RtWkvoEue9L0BPJqYKgww==,type:str]
    OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:uT7QseCGm/yVjyi4homL0d/BTnw5sp1gcnR75THW/ZF42Y2ubiYqQD5Sri3X5scJV1uTzQTy3DSnaAcf/Dy7xEtI5nhsAJOQyb4EJg==,iv:DP1Q1Gra3kyL5oEuV2JLOnKoa/c4NVJ4+UC3x6WVBcw=,tag:34qL8XYrBPTAaGmKWea99Q==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:DbFO0H7uj0ZfDgodiMtD++xYcFTBFYvNko+Mlpaxud1RIjqgb9NGOg==,iv:3aT4z9NoQvOQcx1XDnhP1NnpuKnEvjeKCh5i0OD33c0=,tag:6F2IxpRbwI6Esakl0j8qsA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:I2EBfy4Pm9Hwxs4f35Qx+SUgaZ+94QipcWazrL6WCYG60eRQ2IS4l2z9OKpF2MuUSbqTZK2VVWhKeOOwHGE1vQKIalpkK8S835inBrLFbxgPoj9YDUTOZmGNVM88E4NTKAQ8XHJQ0uDyv2d8lVIv2CgG66lvuUajkdL+ZDfbfIw=,iv:sF5LVucun00nNualIZoXMIpsODkTcH649U1HyJlFQe4=,tag:W+8OY65iGLl2WxalTct3ZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTU5lQzdkYkJWblpObHdC
            MnZSVEdRM3k2U0ZaaG80VldmajVKZFEyWWtrClljM3hPVVN0V1Jzc292TStOR0Nx
            b0FzRnVXUktodXV1UXZoSXpsZHQyMVkKLS0tIElLRUdzSGdyQmVuV3VBSzNIV1U1
            RUV0cmFPejB2a1lwZW9LOVRGbSs5a2sKR4gtczsk4ly/Z7Q4gIpW3IOTFbO36+3u
            f/qWr+86zISOtw/MBsLEqc/Prji81wqe/kdpq7UpH6m3Q3kDR13ylQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-24T15:48:27Z"
    mac: ENC[AES256_GCM,data:zrN0hSm51gaxq5Hawb28Z9b9Efd3pC9h1AIBUjqdl14Q87rQWs/ZeA4+UW/RVruQbnjpbpkb64FrTBLhJp+1z28cG8BvDDTsMP1JEWmQtuH2M9eBS/DZM6CDjfqbDe4tG1WNdlD+8k0rTMvffGva+S4gT1lV9gzm/yQjMJo966Y=,iv:T8nbFKw1n4oHPaRQU5gjrxEP9ggs8tdCS+wxJpyQ3W8=,tag:DFoP9ZetZRH5ZnWUi2n+yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
