---
# yaml-language-server: $schema=https://kubernetes-schemas.minuette.horse/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app invoice-ninja
  namespace: utilities
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: invoiceninja/invoiceninja
              tag: 5.11.6
            env:
              DB_CONNECTION: "pgsql"
              REDIS_DBINDEX: ${REDIS_INVOICE_NINJA_DB}
            envFrom:
              - secretRef:
                  name: invoice-ninja-secret
            resources:
              requests:
                memory: 512Mi
                cpu: 10m
              limits:
                memory: 1024Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 9000
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host "invoice.abchost.nl"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
            - *host