---
# yaml-language-server: $schema=https://kubernetes-schemas.minuette.horse/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mariadb
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: mariadb
              tag: 11.4.3
            env:
              MARIADB_AUTO_UPGRADE: "TRUE"
            envFrom:
              - secretRef:
                  name: mariadb-secret
            resources:
              requests:
                memory: 512Mi
                cpu: 10m
              limits:
                memory: 1024Mi
    service:
      main:
        controller: main
        ports:
          mysql:
            protocol: TCP
            port: 3306
    persistence:
      config:
        existingClaim: mariadb
        globalMounts:
          - path: /var/lib/mysql