---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-outline
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-longhorn
    - name: cluster-apps-cloudnative-pg-cluster17
    - name: cluster-apps-dragonfly-cluster
  path: ./kubernetes/apps/user/utilities/outline/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m