# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    REDIS_PASS: ENC[AES256_GCM,data:8hK3HOLLq5iFwDL1DYsmcXdIzzVlkZ5KaxJbKc49MvPvEax2IKUo0ieaRP6CKL+Y6L4QIJUYh7GNHzP0qTngwg==,iv:1upvP+oZXYqt5QaUnl3SYRHCTkeBuqeP0IgQJZphmIo=,tag:dcSKGXQOsM4WMvF9IeZ5kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeWNaSVFUbjhUMkgycW1E
            bkVlcSttOVljbUNuZHVSeDRwcmF1ZUJ3ekFVCkRqV0sreUJma2lNRXVzRGNYcnMy
            Vk1UUXA2VXk0akxtK3NIMEs3YXhoUWcKLS0tIExJQUV5VVpZbm83cUYzaXdYOGtJ
            T1VlZ1BrSFBzU0NRMWFvRXJIU2EvaHcK+T9HthIneF/mUTqTaE+BLk3BsRc9oU2k
            T+sCJH+Evl+eZqw2pUbj4O6WzOP5YHgDN18+YsDpVq/S4tNnjDmCwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-28T16:26:39Z"
    mac: ENC[AES256_GCM,data:k/XLBeZOpqnoUto3gm9Duls3yoTD+gJkbHlN/Wzl5epNm65D8zoFVxZvdmk5UJTqbxOPRQYQRoSwE1tweX71H6ZAFqYmVedaK7YJzhuZZZMIAk67jYn36yGhsCP1aQdBJpiakuH9Fgf4LytylI+Z5wkmJB3CoKd4IqCkoalSqpU=,iv:u2wdXj8Jq462ciTFnkUz6jD5bXgyFmI/K968AmZj87o=,tag:7fWKCiSlcSSAhAKA7lABUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
