---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-system
resources:
  - ./alertmanager-config.sops.yaml
  - ./grafana-credentials.sops.yaml
  - ./helmrelease.yaml
