---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./nginx-controller/ks.yaml
  - ./blocky/ks.yaml
  - ./ddns/ks.yaml

