---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      blocky:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.26@sha256:b259ada3f943e73283f1fc5e84ac39a791afec7de86515d1aeccc03d2c39e595
            env:
              TZ: "Europe/Amsterdam"
            probes:
              liveness:  &probe
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 53
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  failureThreshold: 3
              readiness: *probe
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                add:
                - NET_BIND_SERVICE
                drop:
                - ALL
        statefulset:
          podManagementPolicy: Parallel
        type: statefulset
    service:
      app:
        controller: *app
        nameOverride: *app
        ports:
          http:
            port: 4000
      dns:
        controller: *app
        type: LoadBalancer
        loadBalancerIP: "${CLUSTER_BLOCKY_IP}"
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP
          dns-tls-tcp:
            port: 853
            protocol: TCP
          dns-tls-udp:
            port: 853
            protocol: UDP
    serviceMonitor:
      app:
        enabled: true
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 30s
            scrapeTimeout: 10s
    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host "blocky-backend.abchost.nl"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      time:
        enabled: true
        type: hostPath
        hostPath: /etc/localtime
        globalMounts:
          - path: /etc/localtime
            readOnly: true
      config:
        type: configMap
        name: blocky-config
        globalMounts:
        - path: /app/config.yml
          subPath: config.yml




