apiVersion: v1
kind: Secret
metadata:
    name: invoice-ninja-secret
    namespace: utilities
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:l8aNh4pNfsKIiEWSKtJF/W8anXyFhh/QvHoJQBykiJBMf33KuUTx2hEMjvirLLlmEx/y,iv:StrKZjBk7cZbrMI+rUdxAodJS7fzwUnGwI8CPDFrLr4=,tag:tytQ9rJ3zX61v4xcpQcO+w==,type:str]
    DB_HOST: ENC[AES256_GCM,data:TDfxxfu/qZrIHZ9+iABXqXzcop19zbJmpX876Lkm7yc+4A==,iv:3wI+4eTARAq0tZ+NMcwkukSzibNoNE/2IjmhQgnDDxA=,tag:HEsmfNYOUX9EDpi7adSINg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:cjLAwA==,iv:xbJwmOec10AATETSjv3rz0M7J7ZaQblSe1P2z50969A=,tag:+lJaaJ7I7Elf2jw/+K4bHw==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:5Ine6IhUELH9MLKbbw==,iv:cyS22hyc6x4k8/V3KiVCHJ+zILTWuQ5TI+JsVlC9+wQ=,tag:ubQUkfzvA9uI5/WnhXVV6g==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:hQ0R4G088P7IYG0lnA==,iv:gqgx7QLBC4hV+DYonbGWPKYEx4Zh9jfgLaK3YPSMTQ4=,tag:8He+IjFJDMAkrQHtQrI+SA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:QIt9o/TXelZKJUevkzaqpEWQrY9oFAvXoYBJqhd4Z8neSC5y4hEQZQpBRn7moSJg7Ofx6jyVcbxrKvg6F9liYw==,iv:Oo3BkBwV73eX9NFLqn1ZhsRFFVPhK2ACo0ftQGaSGr0=,tag:6PfrF9foae0daeA7Vry8sg==,type:str]
    CACHE_DRIVER: ENC[AES256_GCM,data:KAOrzPw=,iv:WNTv4OnrR7pW+Pz8BESfTEEXmz53yMMWYdPyygKAHE8=,tag:A0InC/OF1uv8qM4zT/XcHA==,type:str]
    QUEUE_CONNECTION: ENC[AES256_GCM,data:EygrN1Y=,iv:sO71dD8CQ7jmN0LY6txhkevuBDHZGgc2Fhd5rszGhjE=,tag:XeYvHAWOf6WuKzzxIayx2w==,type:str]
    SESSION_DRIVER: ENC[AES256_GCM,data:2L3R+XU=,iv:N4TBzGcSWeIcIe6GPW+YPYxk6JkeuggtKSRJ2aN7Mdg=,tag:ZBJQiw1tq/6Cdn2ZC9zEOg==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:LjV0CnOCuKwSo8DtV0r7ObyiKdA8Dij37sajV2ha2AmWAbUU,iv:d9Gmf2dLtbVoI+Ivu07CRJ9LlgvVVGwJv8X28UiP0Xg=,tag:3Msnbzs2AjNY4ZV8k1aCZw==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:B4w5zw==,iv:rxi/n1crN9bQPKBMgZtlO6vdAiAL/NKjLRhIuGApHcc=,tag:z4Uo/7wrh8k0hpOO1Euhhg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:vU8t6YKv0i9Fh50rBcwDMKYE6t5FxlbgKc/UIR3VUC6x4A6GjHnZnUgdTE05et5uECp2R+d521FGSbs8kS3hfw==,iv:3T/AASxP08HA9VbURuwNaD+f/Un5OV1Z8iuH8oKVtoA=,tag:fcQ7Qs0FMGLQDEXQ5WqjCw==,type:str]
    IS_DOCKER: ENC[AES256_GCM,data:JvTzxg==,iv:+w0ydQR7g2Qvuc+awhp0V2OdADmwVyOz8Lwjf/pE47A=,tag:GJSN1BUuQblSRc0P8Gw7yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR3JmU25maTgwZUt4SjhW
            SmQ4WVNpMmxLVVBXQUpzUFdOS1R6R0xjY0J3Ck02ZU9qRGltZnV1MU8xYmtWbmla
            eTA0bkpubWM2WmJ5YTVvVnJKK1Q5cjQKLS0tIG9heXN1SWpHSzYvN2tVV1cyZTVy
            UFhZb0V3YktxRVg3Z1YwL2M0bWV2QzAKTaRDpBujzZ7EHh2nqIv267BWKwuoF2zd
            M9s2IUM78VuPOifb4dsJiP3Kr8oinssqR4VCGnHsXpg8+uOJdO0ydA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T14:56:50Z"
    mac: ENC[AES256_GCM,data:A1p8VRtiXirGd2wZDnYv7Nci31Mf6QSZa5tH68IHxkBcwf3aQ6P5PP3CtV0M8Nhya2ZI4cxv5N5cAnUP8264eOuESK/CmKCqoJcjmOoi65VaQUrkdot+9ELLNjtJPHPQ9f498QYxPP1a2Lo+YFCDu/pHQ9yET4Am8XyDCns6AHg=,iv:BnS3niLRsDB0owKqZ8m+igYjor2XRGsduQMxiTnObBs=,tag:8Wj+cL4m5bfk9tDGnkg4cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
