apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
type: Opaque
stringData:
    REDIS-PASSWORD: ENC[AES256_GCM,data:52KFFeTsZFySEp+hV9xKXa0Q8/KxNyp2bBKLmF+jX6hyYdXOeIHCYSalKPBGlUqfP+XdhlzILZuGi5Lez2+30g==,iv:7jTszwYLi4vEmd9Cxs9eUmuZdgeJ8eXmTNCeS+48HsU=,tag:RkqAJpgQA7rT+UXToApVxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRVZvR04wTVF0NU1lcU5H
            cEtZbmtqNXZrbStQYnVoRkRKN0Qvekc4SFVvClU0YlRMa2pmTkRPclN0WTRramtK
            RzF6ejBuaDhXQW85elpPR3J1bjk0NlUKLS0tIFJJakt6bm1SWTMxMmxBYVhWSGVj
            UWF1cURubTVhMkVCYzFpcjlEaFZ4SVUKx4jhiWN+OhCtMsWaRPX8WJN9VeRHBrdX
            jGr6DS8vUrtrWXI34Ho4RvNzISgK6/QCxQxHrWraMqkTHNBZh0BZNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-02T14:28:09Z"
    mac: ENC[AES256_GCM,data:4uwUkRBH8oDpshP3VJjaXhqiOIHVlGJsYpKjIyoWatHjAmEw37ZHMIw0Pssic4SF35kl6mN6Df0VT7E9vNys/HPBf1IpEN0y3ifaFR/vo+Y+TT7vUQvwHLlFFO9lfvL6N5l7XzjieqhPEmHV5kRfZeZ3ALzNaB7ykNZhPDJfXWE=,iv:zUzTkz4y1+vvZ3NwpP+xniajGFrS2Um0jWiyIDRTdBo=,tag:6Q+Ve1bKW5xD66F2Zug+Mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
