---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./externalsecret.yaml
  - ./externalsecret-backups.yaml
#  - ./backup.yaml
  - ./mariadb.yaml
  - ./provisions
labels:
  - pairs:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/part-of: mariadb