apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
type: Opaque
stringData:
    #ENC[AES256_GCM,data:H5A4aiZeu+B3mdLD432tsRg=,iv:hbYBu9GZJbnt5dzh/d4dohsofpCPKK21rGDi3588WUU=,tag:29RnuRlhu3O4RLLo3NLgjw==,type:comment]
    username: ENC[AES256_GCM,data:Zo0tUdzr4VM=,iv:w9Hn0BKkYrdTwrlRi1D7Qs6TrsIZGNC1kATZj2MlTso=,tag:5780f1aFqLwsVxMgs/S4AQ==,type:str]
    password: ENC[AES256_GCM,data:B49obEToKRgwARUXK5Yk470JXs1T4lh7NRkgJERzvRdislyDvw8aHAuyscrqQQADmSNObSf+OD1dtuGh3oMnGQ==,iv:Ilt5KRPiA1lPQGwNPqxkQ25w6HkG9gRIP/KoN8Grdlc=,tag:KIy3pOTWdZ6vsF0T2DkIIw==,type:str]
    #ENC[AES256_GCM,data:Ml/0eT4ejKHrH9kfraPCEmZCSmetaYPSsgBp,iv:XOuu0mPmxoFe8eXiaUL6SqVXujwlUgqPwctjE/wPJ60=,tag:RXk0SMaGeUaAIG9A85RboA==,type:comment]
    backblaze-id: ENC[AES256_GCM,data:hqRkYIDKPWkLhxahdGHINt7+kFoHt7FZSA==,iv:T7PIw0SCzmO7X4TMkvLvm8W3mzI4fJyyAxRL8S68M4M=,tag:zZAFZPlxaAtMEbnSoM7p+Q==,type:str]
    backblaze-key: ENC[AES256_GCM,data:K3wew8v/cVm76AjlE63pEbcUMnFCO43nCelBwQ5DWQ==,iv:P+U3W5G6N43mJWGTNH2UPqtvmacEGetwlxuoEQ2GmXQ=,tag:X1KkYBd+Fi3meRy2nt3hUg==,type:str]
sops:
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
            NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
            RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
            Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
            6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T22:43:41Z"
    mac: ENC[AES256_GCM,data:NZBh8Cw8BuQ6tq4tdLnbQcONJZ/xjU37roUVOOrTFKtZAyitteude4P9ue3V0WWfpx2eGSKePlUzqk8557l3MaD6gm/l2v5O/1Q9kREjDYwHIv/Kfa3h7Xrvk6eLmHNAI9fOAab1V3USM7/JMcxJ/A7VobWcFXjkiLJKNyA1Tgw=,iv:AhTDtCiieBgYfHIXOyW23iLS1dBmgSBf+3IWEp3sVOI=,tag:SU5Kv4SSgaI/Nou7zC0xUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-app-user
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:PypT,iv:MDxOm8jEovklxZ9Q+cBLNRXKZZReBCnztT4McTA+26o=,tag:2a11//tidPLOEE3vQNdXLQ==,type:str]
    password: ENC[AES256_GCM,data:+YFDy/rL80XAZwPMrUKubTHPSa8=,iv:VlAsumXufJjIUntnMsbzwO9j+Lk5FV9KagB2xZj0+NM=,tag:pBRptEsHdcqFL3zJi0rvIA==,type:str]
sops:
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
            NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
            RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
            Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
            6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T22:43:41Z"
    mac: ENC[AES256_GCM,data:NZBh8Cw8BuQ6tq4tdLnbQcONJZ/xjU37roUVOOrTFKtZAyitteude4P9ue3V0WWfpx2eGSKePlUzqk8557l3MaD6gm/l2v5O/1Q9kREjDYwHIv/Kfa3h7Xrvk6eLmHNAI9fOAab1V3USM7/JMcxJ/A7VobWcFXjkiLJKNyA1Tgw=,iv:AhTDtCiieBgYfHIXOyW23iLS1dBmgSBf+3IWEp3sVOI=,tag:SU5Kv4SSgaI/Nou7zC0xUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
