---
apiVersion: v1
kind: Service
metadata:
  name: postgres17-2-lb
  namespace: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres17-2.abchost.nl
    metallb.universe.tf/loadBalancerIPs: ${CLUSTER_CLOUDNATIVE_PG_17_IP}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres17-2
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: postgres17-2
    role: primary
