apiVersion: v1
kind: Secret
metadata:
    name: atuin
    namespace: atuin
type: Opaque
stringData:
    ATUIN_DB_URI: ENC[AES256_GCM,data:/MfRXJhGd8L+3IJJTv1hli6JCyODloUg9GOFXdMEDG/cQtnOI5nClutppd+kMcc9GG0siPp4Jpjb+auKI9EDiiCZ6mBLf6uKeTUDAmMolOyVKiuzFZdPt/ws8Q==,iv:T70xmRhGgU3uFC6u1MVS5qSxCuWPeZWlvON3P09PK18=,tag:himaJdBcg85ZFCKKvnMCAg==,type:str]
sops:
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaDJqSU9YcG93MG93ZnBn
            OVd1VU9vSmRMRmovVXBaMyt2YzA5V2JMZ0dFCkk0MjZ2czl1a3pMczFaNkR4UlVo
            b0FlSFlOTURxSTViOUNQV0xoN05GbVkKLS0tIGt1R2hmREx6ZVZkZkRHRnJ2Zno2
            UWcvK3hsUm9tS0VSaFhVTmhtS2dhZUEKn8d0/1RoEWi89+sd7nI9TuFI+N4V8RCY
            7oKicdeXdP0Oa5sJUUphtPIRVWLeRqlPHGT5GqBo0i7+H1nXiYR+Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T18:57:11Z"
    mac: ENC[AES256_GCM,data:hxwbu8sHI0Bgb4ebACT80LiGZd3NfWvTIhsF17lq76LaDuTSXfKU4K0JgYcQQOoJyL4SQNKrKQ4wUsfeDGxn5Ykvcfui04rKK2volymNBMc3wzwIZbdjg04Y5UGObc3Cw9y8zH2OKmmUyn3MY2Q9n6xao9G7EGxSdKCIC2FyLKU=,iv:GDqmyPITS8XdeeDcPQD5maLSHmLRl/60ivwowhi3d3c=,tag:cr6kFbCPmddZ0IdXgQC23g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
