apiVersion: v1
kind: Secret
metadata:
    name: invoice-ninja-db-secret
type: Opaque
stringData:
    MARIADB_DATABASE: ENC[AES256_GCM,data:6QnxRoVs5u3r5WhefQ==,iv:1fEjlqIqUi4wlqs8XwbQhCClBpcFotS5b65YA1CXrbw=,tag:kUQCfkQ2TTwclTEu6FK7jA==,type:str]
    MARIADB_USER: ENC[AES256_GCM,data:DyarBMhcCyFpQ0s92w==,iv:fo29a27L3rf2t9g3+1ZTq5GVBbk8I25D+pCk4wXZJ34=,tag:mhn+6T+O1PtgWQpoXaTnMA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:jvuJYTLiFpBhdMgHOhnIVoah1Ud/mF+6vw==,iv:CKlAq5ORBy1fjvAtkd1qx/uhJ1a++fa98fAOKPQqq1M=,tag:hfQxJmw9Q3E0crIueSwWZQ==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:eekfT3vXKpV5nrQkqCfpQV0/UKdROdfLew==,iv:XK7KujjQX/I0Y+9lFafk+TxvDy8j5GyRwZoMc2YlQ1o=,tag:TFofKiz5ln3iBR05Z2tJuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNUs5ZDJFUnBBcUpKdmlZ
            TDNab3l4ZEtLRjl2bGxTS1RQcllleTVjOWdVCkhSdUJ6VkphMWh6VXBPdlJqZzRk
            U2VIWElrejE0WW0xajlMUGFFMVZoT3MKLS0tIHhrQWd3UDAyYnFWL1ZjQW5zdWJP
            cDlqbURVbkpzeWdUcU90VGo1UG1ya1kKqe9lGEQAPnSzGOmmVh5PjjehJqBfqZGy
            j2XI/Tut/8RQhMj503eg5GxjXp7xCPSg8s3KestNfsLjYNFNQnV5pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T19:12:11Z"
    mac: ENC[AES256_GCM,data:lH8YX54KSO+J0C8pwjNKM2n6LYyLNVXI+nHdA8Nvdo3NeERCEaBnboZED8YMtu80GkBJWoCwg4Hq/GFwztn11b4GPseNioGu8ISmUwm2ANLG/KQXgHHkdI5j/WjQ4j4FM7oPTfji0GGMl+akkSbz4G3NoIogtnkKpJe224hDwdA=,iv:pEZE+tQhJ48fIcHyaBC39N00m/yWot8vAZcArqq6egU=,tag:n2dx2IyvnBd8AHr0VM2cSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
