---
  - hosts: all
    remote_user: root
    become: true

    tasks:
      - name: Update and upgrade apt packages
        apt:
          upgrade: yes
          update_cache: yes
          cache_valid_time: 86400 # One day
