apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:QJLswvSDhrhldMk1I8JUhInHvR+l2h/yO3JYPIWsR67G0n82Fc+Ypa//4fsGBUpN0+AKKqT/dYeSrsmCj89TgQeZMMpZ084KRGGKEWRgz6vqO3mo7GyqqSquGAuYEzXjczcr+UTzBGRsYrKkhnHTRMpFMBhj58W6EiJo2WgCv+hTfmiTWJyOwk66A+gl2DQW+/CsqdmHrVPV2gwArqDpdi5UPKAgmbNRU+gtTpjBp8+GXpX8bhIIdg==,iv:1HcBRJi2QBdmWiONIu9vVEZmWQX24OXuFN4QCC/9ryw=,tag:GOfoSBKvok5HQCzvvgUajg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxT1R1aXpRa1pvaDkvZlBD
            YWFpbUdFRks3UVhmZGdya3BkVm9Kd05ieWxBCmFRMjhuamNWR29RR21QMHRHT2px
            OE5vRmhLU1NKY3k1TjAvMEExYW1ZcjQKLS0tIE1ON3dqZHJrZk5OQVhxRzRkbFQ3
            aHBkajdvQWM0ejRoNjRodlBkTzExbTQKshm8ioIKh7x0eruT5heBD3yuOFvcuNAU
            Kj5WQ4BIHYHKhdkUo8apzf8daJnn+O3ukaaBOC1C14T71N2xF1MD8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T10:38:55Z"
    mac: ENC[AES256_GCM,data:rZChCH2j3WDLhkGFezmaslZi3B5LT1kiXtmluUr1Z7swAxKVEcQIKoJ+hoKuvjANBISdxzcuk/58SX0e761GqTFU08GWmlesXpUdLSRpznkK7TFnwzVSfjQMAWA3MufdVR78/3NlmFbXpDxj5p29h6jJyNE50Prl/7/yj/U6riQ=,iv:eSCtfWqg7Fexgn7oq/uAxAD2QN/GUNlmyjTpyrX8s3k=,tag:urpv2zO5LmBddyJ4j3foWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
