---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        type: daemonset
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: cloudflare/cloudflared
              tag: 2025.1.0
              pullPolicy: IfNotPresent
            command:
              - cloudflared
              - tunnel
              - --no-autoupdate
              - run
            envFrom:
              - secretRef:
                  name: cloudflared
            env:
              - name: TUNNEL_METRICS
                value: "0.0.0.0:2000"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ready
                    port: 2000
                  failureThreshold: 1
                  initialDelaySeconds: 10
                  periodSeconds: 10
              readiness: *probes

    service:
      main:
        ports:
          http:
            port: 2000