---
apiVersion: v1
kind: Service
metadata:
  name: &app external-pihole
  namespace: ingress
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: pi.abchost.nl
  ports:
    - name: https
      port: &port 443
      protocol: TCP
      targetPort: *port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app external-pihole
  namespace: networking
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ingressClassName: internal
  rules:
    - host: 192.168.2.254
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                path: /
                port:
                  number: &91