---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-intel-device-plugins-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-node-feature-discovery
  path: ./kubernetes/apps/kube-system/intel-device-plugins/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-intel-device-plugins-gpu
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-node-feature-discovery
    - name: cluster-apps-intel-device-plugins-operator
  path: ./kubernetes/apps/kube-system/intel-device-plugins/gpu
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m