---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app outline
  namespace: utilities
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      outline:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        containers:
          app:
            image:
              repository: outlinewiki/outline
              tag: 0.84.0
            env:
              URL: "https://outline.abchost.nl"
              PORT: &outline-port 3000
              WEB_CONCURRENCY: 1
              REDIS_URL: "redis://dragonfly.database:6379"
              FILE_STORAGE: "local"
              ENABLE_UPDATES: false
            envFrom:
              - secretRef:
                  name: outline
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: 4
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      outline:
        controller: outline
        ports:
          http:
            port: *outline-port
    ingress:
      internal:
        enabled: true
        className: external
        annotations:
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host "outline.abchost.nl"
            paths:
              - path: /
                service:
                  identifier: outline
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "{{ .Release.Name }}"
    persistence:
      cache:
        existingClaim: outline
        advancedMounts:
          outline:
            app:
              - path: /var/lib/outline/data
      tmp:
        type: emptyDir