apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: utilities
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:cXFir7AZWcEBS9wjJT4qwpzSMaur7o7vEwGNncWwNSTwlZU/x7SQAkKrs/qj/h3AF2UzPpMxTbZJERALVlduow==,iv:kBEOXc+5NEH2hkK7jOSh6GEY+Y3CMwyelTLtMjazdno=,tag:M78H/lQU6As/I19vGkHwpw==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:322REFsaGjpipkNwTDT9gpMMCg1Cs5CVVQ3xQ6FNlEfIquH4FhaiEfcvLhPGQvQsjDS5gYGezloOSmVOW/0jlA==,iv:oCwufZ9/dbaezfJQChvO4JEzh39uxtOeLNuq+B9j58Y=,tag:BWBceUnUk2T9rUEeZ2dsAg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:lI2QPgwhVFFyyFd9eDZiLdvDDbLIetRd1txZFn009V0AmlnqJ/qetjMXu+hDVfp0gpicmr8krJy1R8dQdRK2egymW9DPhPctzHeQh2dUK7lFiEAVw2Po,iv:NFiWFMK4qf3EsOr1FUNeKwr9g26navS7Y2Z7RwdkNF4=,tag:FXqp58+aTpWhqubWCU83GA==,type:str]
    #ENC[AES256_GCM,data:cJ3ZeQHfNAuvgedEmD0=,iv:Meks5Ox99bowuZBoA4u+4Yc2XD8Fa1MjkRgPIpbPz10=,tag:+NulueIod+9pJy+sLEMweQ==,type:comment]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:slf9XgEQgcdyrm4eFQm4UoSBPRlseSi7mTAjKntq4Ef6J7iKzTMx1w==,iv:cu0/xrrI8dXNthF/D8SND76Vwfqhe08pOYZvAs3gGTo=,tag:SFrah/zdnZUhvlGVTdkGAw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:MoDFhVn9ovYr9aMm+m3t/GX/E4zNRIRUOvZe1/cMe4+uOSzmIIw8t1mxqLbxToHoj+9zzbKkoSLm9c+wi1rgo1rU81kGs5KqXAsOsBhaLDLqEe3rIWVCWzD+0UDB9DSLEeoZS/YQJmK13W1wF+/y9CrofMUtvxYg7D2SOtljSa8=,iv:JaFIUT9xAebijq1S2I5gYjp8bUWcAaTrC+g1Z4h3iZQ=,tag:colP1N6dHsdoPMjHqD81Yw==,type:str]
    OIDC_AUTH_URI: ENC[AES256_GCM,data:98TcG0VE63l7Xsg6OLjHnlA166EWx+BZ9tt/ZvvYmSPznlC6qiW9YwN+PQYsTfk=,iv:ehXLUnlbTKLM/0FohGJWWrWgsTHhJB9GbdVJ5T3/Ik8=,tag:JU6NcBHyNubop+pjLV6WuQ==,type:str]
    OIDC_TOKEN_URI: ENC[AES256_GCM,data:LawyS2THUbr+uOPyHIVettIhCDNNvzWYOwPjeAIuvZ4kDSVvu26pfUXBrA==,iv:aHd50zKfU7QZKNgZ5kbPwDAubfCgJmchIoMojFzxncQ=,tag:jw83lu9FqL5ad5sYv4EP7g==,type:str]
    OIDC_USERINFO_URI: ENC[AES256_GCM,data:buEUDjyfDiHbKv2C3vVdXezqzLCZkMd/WMIHr4j5pQa6U2qQ6thIVmDjNNW1VQ==,iv:ZuNMpLpflT7kfAxtiMVJTJwjbce+cp9r6k6Eh3hFUWo=,tag:W/BWyrBpF7ZXhraB56OrPw==,type:str]
    OIDC_LOGOUT_URI: ENC[AES256_GCM,data:QIxApCUWxKMT+nMVKXjy1drNpLkllw3vN+oDJokZAOFDiy3vmF78LJTQAmDUSHNX6a0O57Am0kGB,iv:NNOvVHiV+wsCH9PcgJJw+M3U2+pvEZ7e4CsZFIiDDMc=,tag:AD8cy7brYlA5BXh1EAbs8A==,type:str]
    OIDC_USERNAME_CLAIM: ENC[AES256_GCM,data:ofWd0MDlZ+m9OH6piY2Zm9Bl,iv:XLaVdDKrMCYYJLkctPumY2X0eaMZ+lKJnAe5lAVofpU=,tag:B42S1RNnveqbh24rBT5+9w==,type:str]
    OIDC_DISPLAY_NAME: ENC[AES256_GCM,data:nZSczkhbMMZW,iv:PRowPZ60muS6kRNLj2HeqzwobRsdZwFVd+6yh5KmLiE=,tag:eg+4IyDA89aCKkME2vmItg==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:vkqN2fmhKri+we+yjJyWr77KP68=,iv:AvvCI3/QKuj5gvBgWrxFq3bfgbbEu23MPCLAvpJ82fc=,tag:oOl8qsqrhIjPk9IS6Klc2A==,type:str]
sops:
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMHpOc2JYUDJsZDZ3SEp1
            QnQ1ZjE5eVhjRjJwRVZBaEZIOFMwZUJkTEU4Cjk4UlZPT2M5NU9QS3IwTWt1RHVG
            MlM3eEEwRFg2bkpWc2NFdDFKNWh2bEUKLS0tIEdDZWlaYmVycnpKTVFqQTBmN1ZD
            S21JaU4rUUFRdUhFQ1FHV2dBSXQ2d28KYOvBEx0R/W4Wk7IcbI7ElbnSYuQnft4w
            2jjTqJwpbO97HqHFz2HmvCeNcjpRXxBwUb8zUa/8u7GdnUwJO3ihCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T16:20:49Z"
    mac: ENC[AES256_GCM,data:EvOdoDVtspc4xBMR1YnAryuhrbPW7/3OcIhv5vT3BscPynhNvQccfnbKlVMfsnstQX1VfCexc9PMn84YtyBclL4TzfPMfOub2x29W7NgxIvc5EgdAomNSe4kxDJX+nSRrBKaZft57Y+8r6uWKe2rILzP3J+QDfiusUrUsNuD9cg=,iv:urASUcHxAnRMZh3BaTfw2QHPR+hVM9bHBlZHRmXozis=,tag:gokii+JBtS1u6QYxlw1xug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
