---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-prowlarr
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-longhorn
  path: ./kubernetes/vpn/prowlarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
