---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-machine-learning
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: immich-database
      namespace: immich
    - name: immich-typesense
      namespace: immich
  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
    image:
      repository: ghcr.io/immich-app/immich-machine-learning
      tag: v1.78.0
    strategy:
      type: Recreate
    envFrom:
      - secretRef:
          name: immich
      - configMapRef:
          name: immich
    env:
      - name: TRANSFORMERS_CACHE
        value: /cache
    service:
      main:
        ports:
          http:
            port: 3003
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 2000m
        memory: 4Gi
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    persistence:
      cache:
        enabled: true
        type: pvc
        existingClaim: immich-machine-learning
        mountPath: /cache
