---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: indexers
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: linuxserver/prowlarr
      tag: 1.10.5
    strategy:
      type: Recreate
    env:
    - name: PUID
      value: 1000
    - name: PGID
      value: 1000
    service:
      main:
        ports:
          http:
            port: &port 9696
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /ping
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/prowlarr/hotpink.css"></head>';
            sub_filter_once on;
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: "prowlarr.abchost.nl"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: prowlarr
        mountPath: /config
