---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      prowlarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/prowlarr
              tag: 1.18.0.4543@sha256:34f4eb42bce895c0c5388ed8f81095dd8ae50dad0fd6117fad2765c5ee16d62d
            env:
              COMPlus_EnableDiagnostics: "0"
              PROWLARR__AUTHENTICATION_METHOD: External
              PROWLARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              PROWLARR__INSTANCE_NAME: "prowlarr"
              PROWLARR__PORT: &port 80
              PROWLARR__LOG_LEVEL: info
              PROWLARR__THEME: "dark"
              TZ: "Europe/Amsterdam"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
        pod:
          securityContext:
            runAsUser: 101000
            runAsGroup: 101000
            runAsNonRoot: true
            fsGroup: 101000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [10000]
    service:
      app:
        controller: prowlarr
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/prowlarr/hotpink.css"></head>';
            sub_filter_once on;
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.abchost.nl"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: prowlarr