apiVersion: v1
kind: Secret
metadata:
    name: typesense
    namespace: immich
type: Opaque
stringData:
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:OEV9uuqyxUYcS+eywYjBu2FDrAOPgWgQlAxmlmuDeYkd+p5pK9x198Nrkin9V0oUPq3Knla9yQbg5oiv9XbC5g==,iv:q6hkQoH0Lp5F09rUOQgU0G1C/maFmxnYnntiyRps9gk=,tag:IMiYZVjc4aGyl1UaG36Hvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaU1yR0JaL2YzTHI4MHN0
            SFRwa2RKN2RENFNUVXFKNTdRUHliRTV1WUhnClVkZlE5UHNTM0xUV2czMjNuWUJi
            R2lsUWFMNmU0WlVmNUV6engwZGY3QlUKLS0tIDVvTnVoQ3dHeW5uRWw2RVhXdjho
            eDF6dkJaLzc3M1UzN05rOVFHQUdBUm8KHn7LmGM78C9bEl7fTDgd+SQA2qZ6x6iK
            W/ymoXdEriVnn3243BHTALgoArjWDO2jfsl3SAymQRAfO3QJmyHPJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-02T18:05:48Z"
    mac: ENC[AES256_GCM,data:SJYb5TZHNZ1byfCZz7vuPClXNuFDNB/yYg738fR4weoSTJOu4J9ITZvIcTMQMgbwGcOwBkxZyXZR6qP9FG9HsCXLu2joCNs9Gg6S666d+B6PVHxTqoeF60w43VdPUuMoueA/jnmWay+uCthzAAGZunB9R6dLsIhElR5UR68Z5+U=,iv:zcCFwM0wXjihN2VU9AsT8s/hKls2G3fbXok+PWD4YCQ=,tag:oMPDXsrH42XELYxfHZGofw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
