---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./immich/kustomization.yaml
  - ./indexers/kustomization.yaml
  - ./media/kustomization.yaml
  - ./torrent-clients/kustomization.yaml