---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-apps-intel-device-plugins-gpu
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.32.1
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: cluster-apps-intel-device-plugins-operator
      namespace: kube-system
  values:
    name: intel-gpu-plugin
    sharedDevNum: 3
    nodeFeatureRule: true