---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgadmin
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          volume-permissions:
            image:
              repository: dpage/pgadmin4
              tag: "9.6"
            volumeMounts:
              - name: pgadmin
                mountPath: /var/lib/pgadmin
            command: ["/bin/chown", "-R", "5050:5050", "/var/lib/pgadmin"]
            securityContext:
              runAsUser: 0
        containers:
          main:
            image:
              repository: dpage/pgadmin4
              tag: "9.6"
            env:
              PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
            envFrom:
              - secretRef:
                  name: pgadmin-secret
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      internal:
        enabled: true
        className: "internal"
        hosts:
          - host: &host "pgadmin.abchost.nl"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      time:
        enabled: true
        type: hostPath
        hostPath: /etc/localtime
        globalMounts:
          - path: /etc/localtime
            readOnly: true
      # Configure the main configuration storage location
      config:
        enabled: true
        existingClaim: pgadmin
        advancedMounts:
          main:
            main:
              - path: /var/lib/pgadmin

