apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: database
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:P89+EQ/jKGV4dJpfilRhLxGHEQ==,iv:FCmcTCBg1mPISo1FL7eapFzNScTsRKT9ih4MMwMmncQ=,tag:ZFuKxfjpHkQeg+TY828R/A==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:KqO0NKRMK0pQ9Lf12qu0LAE6Vb5aXkxrOBQXs2/+rjr6jkrAyNQ11xmYl6IuwwOZ+Q==,iv:O3kAfg1dMPNbk6HgFweCoTC5JAh5S82mcGPa4jjpPWw=,tag:W7tzqhZiPwlm4w9n/zL0rQ==,type:str]
    PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:2OGwQaMHDgNk4Q==,iv:Xo3UnqoYnmwVDqvU4UiUAVMbJ0Ituvobh8/yhNTU0gE=,tag:3wEoL8adLOBk52i+taNnVQ==,type:str]
    PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER: ENC[AES256_GCM,data:GGmLKA==,iv:H1HsypMRFu4L4VrmRvcm0qXdYHelVaTcdRARmKlofW4=,tag:IgXdem7tftQ+Mn+LjWUCDA==,type:str]
    PGADMIN_CONFIG_OAUTH2_CONFIG: ENC[AES256_GCM,data:ySklmZp6gm9//CKNJnQ4PNHIPaMjuBrMRMmdj3HqEgfQA5hzRpTVmlmToRQKxBgA8SZ4cZzkiHT3IaiOy9ZrmQkRh9UxXHmIRpReuD/sMXWssVpjuUod6tC2VTF38+NDkTMrxRdySZsyt6QXOTslWzIsPAF8opSQnZgGyLJrgvLiuN9N0+hhuD/DQNSc4p2OJkTncCX7F/JFYZw3/giPwkW3Qu0EZx6b71MjBDbjY/j1U6FV/MJsaF9mXsVV8YuKSjToFUCM5zmPsU7cLPUGeajhlTwLrJir1dnIcVNXAwpcAcbjhXDqUJ4uf49ZEXeONusBQ9bbu6UE/cUb7YAmtZNEbSd2UPd8iNaU+lyTu3/K7xRYMu1iDQT0/wjqnSeDvbmmJzV1tDP7CSuNuTPgY8gx2daqiPqZbAwI3S+4XrDqG3xYcskFkEeXdmZ1tv6rX/vVpZoamm/SwNCUAZ1Tp8EAToE0EOw2Lsg1PSOH/r/1F1IycwpOyOacPHkxCs9BatADCEK24HOEKTwlvWtv6gvCFDN4VAnLsA4GIZQ0oonRSwgwr2iiXzfL9R5f08AofuqnGTAdnQDZf30xnR1goYpzEQcfl3YZnZ7EZlpPYJjKZtkeTeaT3IW4cdyx4kk7u4mmYmi1wVx370PwIFMV8jgUGneBOYm5B14MVp5v+RKwB7NTlQW9Cd+7qi0CqwYas/XHHhzldQ5+1sdnnl2Gv8ln5HxVzm8UoVWcR74Pw8Kf3Rtnhp2iizt+Wf28F3Q8fy1Sp3CjnI5hdrUd+TmngiW3qZiPvSsHhbYfphVuGZ+s0RRZYnbIllI0xuwf4oOTREXLYChGl9RLnw6t5xk9JHAaKlKvMtN8mdKk8d21dzQFkfHzJ1q6+vf7XPKX6yuWo/ayHfB1N9wT6BwCC3tzXfO3tPHfbAlnRxFw3lFoBTOanI/RGzIzbFSqUqNLMvtuPuXT8CRSfhbmv660Pky9T2i3FRLlsxrfgaeo6dd4mdLiE+dTxw==,iv:8A+dKvGjW22Dx33rrnqIaRBfy5H3TYtNVXiMyqc5kLE=,tag:GxZhKoGFffqfTFK7dsxcEg==,type:str]
sops:
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbVBzeUZhNU84dDRMTWJY
            VFpBcU9Mb29hWkd2OWhrbUhjS0ZtUjJqeVc0Ci9hUjYzdlFQVTF5UkUyN1BHZjVI
            dXk3WDZCZjFhNVlrOVFHOW1NdFdCamsKLS0tIG9HMkh6aE0xRlc1YURmR2FWV2Vt
            U2tYMGRLdy9hOE5iQnVHUmZMb0pOUTQKy/SVfvxqCpd90VCj6PTxrXCvwVOWAVFz
            8HQMoEh8AUYSJ0eDbBYDqvuxYW1T7VMy+MOzAyEyZnceiG3lLh7qkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T23:14:20Z"
    mac: ENC[AES256_GCM,data:4zIBU8JQTkReb7RB47J5MGrC215sOC43Igfk0W61Dz+g0ZVa05H+J4z2Q3u2Q8q97mkLLCrmVrSkzG9twruVNkW0o/ppba0xN6eumfQ90P9Qu4B/0uItNwKDbxHffJYy1LeYQPEIDmi59zwworHYQx2HGbZt1K0/7Gw2/7hE6Ew=,iv:TbgcibP97QBg033L+GamZ8uDw6jCxUnGVlPasByUL+8=,tag:g7maKciCLDqstqWSlhlbgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
