---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      lidarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/lidarr
              tag: 2.11.2.4629@sha256:c5b3b5e0c9825555ff542272a9d18eec9b0d70cb80b610b8f4efc848dff54021
            env:
              COMPlus_EnableDiagnostics: "0"
              LIDARR__AUTHENTICATION_METHOD: External
              LIDARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              LIDARR__INSTANCE_NAME: "lidarr"
              LIDARR__PORT: &port 80
              LIDARR__LOG_LEVEL: info
              LIDARR__THEME: "dark"
              PUID: 101000
              PGID: 101000
              UMASK: 002
              TZ: "Europe/Amsterdam"
            envFrom:
              - secretRef:
                  name: lidarr-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
            securityContext:
              runAsUser: 101000
              runAsGroup: 101000
              runAsNonRoot: true
              fsGroup: 101000
              fsGroupChangePolicy: OnRootMismatch
              supplementalGroups: [10000]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
        # pod:
          # securityContext:
            # runAsUser: 101000
            # runAsGroup: 101000
            # runAsNonRoot: true
            # fsGroup: 101000
            # fsGroupChangePolicy: OnRootMismatch
            # supplementalGroups: [10000]
    service:
      app:
        controller: lidarr
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.abchost.nl"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      time:
        enabled: true
        type: hostPath
        hostPath: /etc/localtime
        globalMounts:
          - path: /etc/localtime
            readOnly: true
      run:
        type: emptyDir
        globalMounts:
          - path: /run
      config:
        type: nfs
        server: "${LAN_TRUENAS_IP}"
        path: /mnt/MAIN/miscellaneous/config/lidarr
      media:
        type: nfs
        server: "${LAN_TRUENAS_IP}"
        path: /mnt/MAIN/media/
        globalMounts:
          - path: /mnt/general/
      music:
        type: nfs
        server: "${LAN_TRUENAS_IP}"
        path: /mnt/MAIN/miscellaneous/music
        globalMounts:
          - path: /mnt/general/music